### ISSUE TITLE
[question] ffmpeg: encode-only (minimalist) build possible?

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan-center-index#10571]
Hi,

I don't need playback, OpenSSL, OpenJPEG, pulse, etc etc.

I just want to encode some frames into a video file.
I'm still new to conan, and in the past have just used ffmpeg's avcodec, avformat, swscale, swresample, and avutil.

All the defaults are set to true, so even if I list all the options and set them to False,
who knows if the next recipe version will add another option set to True.

Is it possible to create some 'group' options, so the default is "everything", but that could be disabled for "encode_only" or similar?
Wouldn't that make for a lighter set of compiled libraries to deploy with programs?
And less dependencies to compile...

I see with_freetype has to be disabled if I disable avdevice, for example.

Or is it better/easier to just compile everything all the time?

cheers,
Paul

**Comment by uilianries** [comment]
If a new option is added to a new version, but is not compatible to an older, we just remove it in the recipe. Also, if you are not confident about updating your recipe, you can use [lockfiles](https://docs.conan.io/en/latest/versioning/lockfiles/introduction.html) to use a specific package revision.

Conan supports wildcards, but not to any option, only to any package (e.g. `-o *:shared=True`), so you need to do it manually. 

You can't use subgroups, instead, there is [ANY](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#options) option, which accepts anything and calculates the package id according the option value. So, you could pass a list of options, for instance `"-o ffmpeg:codecs=foo,bar,qux,baz"` then, parse it in the recipe.

Usually Conan prefers explicit than implicit, including for options and commands (this will be more evident on Conan 2.0).

You case sounds fair, as FFMPEG accepts a large number of features, which make a bit more complicated to customize , but, it's not possible to change ffmpeg recipe to a more generic usage, because it may break users which are using a custom set of options and its recipe pattern with all explicit things. So, I recommend you using a `conanfile.txt`or lockfile with your specific options.

**Comment by paulharris** [comment]
Closing this in anticipation of PR #10877
