### ISSUE TITLE
[package] hdf5: fix license + add support for szip

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#1072]
- HDF5 license is BSD-3-Clause, not MIT.
- Now that szip and libaec are available in conan-center-index, option to enable szip support can be added to hdf5 recipe.
- I think that source code should be downloaded from https://portal.hdfgroup.org/display/support/Download+HDF5

**Comment by Morwenn** [comment]
Good catch for the license, I don't know why it's "MIT", I probably copy-pasted another recipe to create this one and forgot to change that bit. Good catch.

Concerning szip I just opened a pull request to fix the `find_package` as you can see above, so we better wait for that one to be accepted first.

I did consider fetching the source code from the official website first, but it has different CMake source releases for Unix and Windows. I'm not sure what the difference is which is why I originally settled for the live-clones repository on GitHub (the good GitHub uptime compared to other sites helped too). Are there differences that need to be taken into account between both?

**Comment by SpaceIm** [comment]
About hdfgroup.org, I've encountered the same issue with hdf4, therefore yes it's probably a better idea to keep live-clones :)

For szip and libaec, I think you can try to add the options into hdf5, it should work I guess (it works in hdf4 recipe, which has similar build scripts), even without proper cmake_find_package names.
You can reuse what I did for hdf4: https://github.com/conan-io/conan-center-index/pull/1070/files

**Comment by Morwenn** [comment]
Weird, it didn't work when I tried: the `find_package` failed, which is why I added the `cmake_find_package[_multi]` names, otherwise the change seemed pretty straightforward (I originally planned to just copy what we already have for zlib but I'll look at what you have).

By the way I don't use HDF5 directly myself, I only needed it as a dependency for several libraries, so if you actually use it you'll probably want to take over the maintenance of the CCI recipe at some point.
