### ISSUE TITLE
[question] What are the obstacles of merging PCL library for now?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan-center-index#10976]
[PCL(Point Cloud Library)](https://github.com/PointCloudLibrary/pcl) is a famous C++ library. However, I noticed that it is not supported in ConanCenter for now. 

Originally, I decided to post a library request for it. Then, I found that there were already some PRs trying to merging this PCL library. However, they failed. What are the obstacles of merging PCL library for now?

- https://github.com/conan-io/conan-center-index/pull/1891
- https://github.com/conan-io/conan-center-index/pull/4982
- https://github.com/conan-io/conan-center-index/pull/9055
- https://github.com/conan-io/conan-center-index/pull/9057
- https://github.com/conan-io/conan-center-index/pull/9078

For now, I'm not capable of helping this ,but I just hope PCL can be supported in ConanCenter as soon as possible.

**Comment by jcar87** [comment]
Closed via https://github.com/conan-io/conan-center-index/pull/18389 - thanks @EstebanDugueperoux2  for your efforts.

Thanks to the PCL maintainers and contributors as well - there is an investigation here related to high memory consumption during compilation due to template instantiations https://github.com/PointCloudLibrary/pcl/issues/3414#issuecomment-1334684151, which is addressed upstream in https://github.com/PointCloudLibrary/pcl/pull/5764, as well as the `PCL_ONLY_CORE_POINT_TYPES` cmake option, which is enabled on all of PCLs CI plans.
