### ISSUE TITLE
[request] qt-advanced-docking-system/3.8.2: Corresponding every Qt version?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan-center-index#11015]
### Package Details

  * Package Name/Version: **qt-advanced-docking-system/3.8.2**
  * Changelog: **https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/tree/3.8.2**

### My Questions

This library is kind of a plugin of Qt. But I noticed that there is only one version of it, `3.8.2`, in ConanCenter. And its dependencies is `qt/5.15.2`.

Is this library supposed to have all the corresponding Qt version available in ConanCenter?

Suppose I choose `qt/6.2.0` and I want to use `qt-advanced-docking-system`. However, there is only one version with its dependencies of `qt/5.15.2`. If I add `qt-advanced-docking-system/3.8.2` into my recipe and install it as well, then there will two different versions of Qt.

**Comment by hnOsmium0001** [comment]
If you specify `qt/6.2.0` in your own `conanfile.{txt|py}`, then conan will pick that version instead of the one specified in QAds's recipe. You will also get a warning along the lines of `
WARN: qt-advanced-docking-system/5.15.2: requirement qt/5.15.2 overridden to qt/6.2.0`.

Of course that means you will have to build QAds yourself, and there may be bugs because this configuration is not tested on the CI.

**Comment by Bueddl** [comment]
Building with a different qt versions indeed fails since the recipe contains a patch that hardcodes a includefile with the *required* qt version, instead of the actual selected qt version.

**Comment by czoido** [comment]
Thanks for reporting, closing as it's already in Conan Center.
