### ISSUE TITLE
[service] ConanCenter is down, times out

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan-center-index#11622]
``conan install <pkg-ref>`` from conancenter timesout.

**Comment by faustoFotokite** [comment]
Experiencing the same issue. The following commands timeout `conan install <pkg ref>`, `conan search -r conancenter <pkg search pattern>`. The following is an example out put for the case of `zlib`:

`zlib/1.2.12: Trying with 'conancenter'...
ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by ReadTimeoutError("HTTPSConnectionPool(host='center.conan.io', port=443): Read timed out. (read timeout=60.0)"))

Unable to connect to conancenter=https://center.conan.io
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
`

**Comment by sersoftin** [comment]
same error

**Comment by Docteh** [comment]
https://status.conan.io/ still says its down, "major outage" and "Investigating", but some I saw some CI builds go through for a project that relies on conan.

**Comment by jgsogo** [comment]
Back on track. Sorry for the inconvenience.
