### ISSUE TITLE
[package] libpq/*: static MinGW build

### ISSUE THREAD

**Issue by senr80** [conan-io/conan-center-index#11716]
### Package and Environment Details

* Package Name/Version: **libpq/\***
* Operating System+version: **Windows 10**
* Compiler+version: **MinGW/GCC**

Commit 2f3a500 introduces a check that is supposed to prevent static builds in MinGW (later moved to the `validate()` method). But the condition for this check here tests for `options.shared == True`, so it raises an exception for building a shared library. As I understand, the opposite should be the case.

For curiosity: What is actually the reason for this limitation? I couldn't find any explanation for this in the internet.

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/pull/15305 should fix this issue by preventing static build, and build shared by default with MinGW. For the reason, well all I can say is that upstream build files are doing weird things which prevent to get the static lib, either because it's overridden by import lib of dll or some other weirdness.
