### ISSUE TITLE
[package] jsoncpp CMakeDeps new target name?

### ISSUE THREAD

**Issue by n00b42** [conan-io/conan-center-index#12616]
### Package and Environment Details

* Package Name/Version: **jsoncpp**
* Conan version: **conan 1.51.3**

### Steps to reproduce

Using the CMakeDeps with a dependency on jsoncpp
Some weeks ago the project linked against `jsoncpp:jsoncpp`, but tested just recently conan exports a target `jsoncpp_lib` breaking the build.
(Note: all other linked library targets are still in component a:a form)

Factors: newer conan version, jsoncpp v2 recipe update

### Logs

-- Conan: Target declared 'jsoncpp_lib'

**Comment by n00b42** [comment]
I think its caused by the jsoncpp conan v2 support recipe update: https://github.com/conan-io/conan-center-index/commit/882399ec87db606303e1fab11fdb845266f54410

**Comment by SpaceIm** [comment]
Indeed, and it's not a bug. The CMake imported target name in CMakeDeps was wrong before https://github.com/conan-io/conan-center-index/pull/12362

**Comment by SpaceIm** [comment]
Official imported target of `jsoncpp` is `jsoncpp_lib` if shared and `jsoncpp_static` otherwise. conan-center recipes follows upstream names conventions, and `jsoncpp::jsoncpp` is and has never been an upstream target. It was indirectly defines by conan generators in cmake_find_package generators because there was no way to properly emulate these targets without first creating this undesirable target, and it was wrong in CMakeDeps because has been updated for CMakeDeps few days ago.

**Comment by n00b42** [comment]
I see, I understand the intention to adapt it to upstream.
(However, its a pitty this breaks our builds as they have been for now)

Thanks for the explanation.

Just as reference: Some upstream issues regarding the imported target question: https://github.com/open-source-parsers/jsoncpp/issues/1234 https://github.com/open-source-parsers/jsoncpp/issues/927

**Comment by SpaceIm** [comment]
> (However, its a pitty this breaks our builds as they have been for now)
For reproducible builds: https://github.com/conan-io/conan-center-index/blob/master/docs/consuming_recipes.md

**Comment by n00b42** [comment]
Thanks for the hint. Will have a look at it.

**Comment by n00b42** [comment]
Considering that this "issue" is expected behavior I will close the issue.
Thanks for the clarifications and info.
