### ISSUE TITLE
[question] Boost: can you select a subset of libraries

### ISSUE THREAD

**Issue by peter-moran** [conan-io/conan-center-index#1298]
Using the boost recipe, is it possible to only use a subset of the boost libraries? For my company, this would help enforce our rules that only a subset of boost may be used.

I see that the recipe lets you specify `without_<library>` for some of the libraries, but not most. I'd rather something more like [BCP](https://www.boost.org/doc/libs/1_72_0/tools/bcp/doc/html/index.html#bcp.syntax.module) which lets you provide a full list of the modules you want.

**Comment by uilianries** [comment]
> I see that the recipe lets you specify without_<library> for some of the libraries, but not most

If some library is missing, we can add by a new option, no problem.

> I'd rather something more like BCP which lets you provide a full list of the modules you want.

That's not possible, otherwise, users will two ways to do the same thing, which would add a new complexity to the recipe.

**Comment by peter-moran** [comment]
I think that `without_<library>` only applies to libraries that need to get compiled, which is why the list does not include any header only libraries.

In the end, it looks like my best option is to use conan packages that wrap individual parts of boost, as done by the bincrafters version of boost: https://github.com/bincrafters/conan-boost. That way I can include them as needed.

**Comment by axalon900** [comment]
Well, the bincrafters modular boost hasn't been updated since 1.69, so I suspect it's quite a lot of work to keep up, given how there's cyclic dependencies and what-have-you within the libraries. BCP does things on a file level mostly. I know BCP has gotten library-level features but AFAIK that's new and still somewhat experimental.

The boost recipe is very complex, but last I checked it really only takes care of not compiling certain things. Saying `without_<library>` makes it so that part of the code isn't compiled, but I'm not sure what that means for the headers. I know setting `header_only` doesn't do much besides set the package_id and bypass the compilation step, so as far as I can tell it doesn't affect which headers end up in the package, so you end up with a bunch of header files you can't use. That doesn't bode well for this request.

**Comment by peter-moran** [comment]
It looks like the Bincrafter's Modular Boost project is abandoned, as you say, but there appears to be light at the end of the tunnel for users like me who want to only use subsets of boost.

In particular, [this SO post](https://stackoverflow.com/questions/63508786/install-only-a-part-of-boost-using-conan) says:

> The idea will be using Components instead of creating a new recipe for each module. Why? We learned from Bincrafters that's hard to maintain, some fixes can affect all modules and replicating will require more effort.

and

> Currently, there is a Pull Request under development to provide Components in Boost. From Bincrafters side, the modular Boost update is stopped due the Conan Center Index's advantage. One of main challenges is solving the cyclical dependency between Boost's modules, in Bincrafters we did "manually", but now in CCI we are using boost-dep, which will be much better.

It looks like this will be implemented in #2097

**Comment by IvanRibakov** [comment]
Looks like https://github.com/conan-io/conan-center-index/pull/2097 has been merged for some time now. Does this mean that it is now possible to "shake down" unused parts of boost and only compile the ones that are in use? If so - are there any examples of how to configure it in `conanfile.py`?

**Comment by andrea-cassioli-maersk** [comment]
Any comments on the question above?
