### ISSUE TITLE
[question] zlib without config.yml

### ISSUE THREAD

**Issue by IceflowRE** [conan-io/conan-center-index#130]
Is that intended and if yes, what reasons?

**Comment by uilianries** [comment]
Hi @IceflowRE !

The reason is because all folders name are using a specific version.

Other projects, like fmt, are using the folder name "all", but C3I is not able to understand which version is related to "all", so we need to map using the config.yml.

Thus, if your package doesn't contain a generic recipe, but a specific per version, you can use the same version as folder name, avoiding the config.yml

**Comment by IceflowRE** [comment]
Oh ok, but bzip2 uses still a config.

**Comment by uilianries** [comment]
That's not required, but is harmless.

**Comment by lasote** [comment]
If you need more info, feel free to write again or open a new one!
