### ISSUE TITLE
[service] Update Windows SDK on CI nodes 

### ISSUE THREAD

**Issue by HappySeaFox** [conan-io/conan-center-index#13159]
Blocks https://github.com/conan-io/conan-center-index/pull/13000

Compilation of my recipe on the CI fails with syntax errors: https://c3i.jfrog.io/c3i/misc/logs/pr/13000/19-configs/windows-visual_studio/sail/0.9.0-rc1//3158f96973765e62212b729a24065a25fb6a30d1-build.txt

>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(487,17): error C2059: syntax error: '/' (compiling source file C:\J\w\prod\BuildSingleReference\.conan\data\sail\0.9.0-rc1\_\_\build\3158f96973765e62212b729a24065a25fb6a30d1\src\src\libsail-common\log.c) [C:\J\w\prod\BuildSingleReference\.conan\data\sail\0.9.0-rc1\_\_\build\3158f96973765e62212b729a24065a25fb6a30d1\build\src\src\libsail-common\sail-common.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(502,17): warning C5103: pasting '/' and '/' does not result in a valid preprocessing token (compiling source file C:\J\w\prod\BuildSingleReference\.conan\data\sail\0.9.0-rc1\_\_\build\3158f96973765e62212b729a24065a25fb6a30d1\src\src\libsail-common\log.c) 

Similar issue: https://github.com/microsoft/vcpkg/issues/15035, https://github.com/conan-io/conan-center-index/issues/10999

Maybe it's an issue with the Windows SDK version installed on the CI nodes? Quote from the vcpkg bugtracker:

>This issue should be fixed in Windows SDK 10.0.18362.0 and later versions. please update the version of your Windows SDK.

**Comment by HappySeaFox** [comment]
As per https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md#windows Windows SDK version is `10.0.20348`. However, from the log file I clearly see that `10.0.17763.0` was selected from some reason.

**Comment by uilianries** [comment]
@HappySeaFox that markdown is updated manually, it can be outdated.

**Comment by HappySeaFox** [comment]
Blocks https://github.com/conan-io/conan-center-index/pull/13245

**Comment by HappySeaFox** [comment]
Indirectly blocks https://github.com/conan-io/conan-center-index/pull/13406

**Comment by SpaceIm** [comment]
Maybe also https://github.com/conan-io/conan-center-index/pull/13696

**Comment by HappySeaFox** [comment]
Guys, any progress?

**Comment by uilianries** [comment]
@HappySeaFox The SDK is installed. Now it need to be configured in Windows machines. It should happen during this week.

**Comment by SpaceIm** [comment]
Any progress? Windows agents still run the same SDK.

**Comment by uilianries** [comment]
@SpaceIm not yet, but it's listed to be done. Right now, we are working on Mac nodes, to be able to run more than one version. It should solve the problem related to CI bottleneck with Mac.

**Comment by prince-chrismc** [comment]
I think this can be closed since Jasper was able to merge 🚀

**Comment by HappySeaFox** [comment]
I think it's not a good idea. I opened the issue not because of jasper but because my project, sail, which also wasn't able to build. Any current or future C99 project will fail. When you try to bump it's dependencies for example. Closing the issue basically means that you will need to copy-paste the workaround across the repository for any C99 project.

**Comment by uilianries** [comment]
@HappySeaFox This has been investigated and many more information was found by @jcar87, but in summary, we have some internal options, like, updating conan global conf to enforce CMake to use the latest SDK version available in the CI machine. Meanwhile, any recipe can use the very similar workaround used [here](https://github.com/conan-io/conan-center-index/pull/13285/files#diff-f6124e4b428a345d887d0178c50458fbdf98abb78cd99f42879646a252686d73R74). I'll open a PR to your pull request, adding such piece of code.

**Comment by jcar87** [comment]
We have identified the underlying issue and are working on deploying a fix to all agents that will make the workaround unnecessary. 

The correct SDK version is (and always was!) installed on all Windows build agents, the issue here is related to how CMake chooses the SDK version for the "Visual Studio" generators. The way this is done by CMake is *not* documented (see [here](https://cmake.org/cmake/help/latest/variable/CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION.html, it mentions that it "chooses" a version, but it doesn't provide any details as to how it makes the decision). In our internal testing we were getting different results on different machines with the same SDK versions installed - until we understood what the issue was. 

We are currently working in deploying a more permanent fix. Once that is done, we will update and eventually close this issue. Thanks everyone for your patience!

**Comment by HappySeaFox** [comment]
I think filing a bug to the cmake bugtracker is a good idea as well.

**Comment by HappySeaFox** [comment]
Maybe it's a silly question, but is it possible to simply uninstall the old SDK ?

**Comment by uilianries** [comment]
> Maybe it's a silly question, but is it possible to simply uninstall the old SDK ?

That's out first idea, uninstalling all old version, but it's not just a simple desktop machine. We would need to update multiple CI machines and update some configuration scripts too. Indeed it will be the future action, but as workaround, we are forcing Cmake meanwhile. Good catch bringing us that idea!

**Comment by jcar87** [comment]
> I think filing a bug to the cmake bugtracker is a good idea as well.

A bit of an update on this - it looks like this behaviour is already fixed in CMake 3.27, and there's a new policy for the Visual Studio generators to use the latest version of the Windows SDK available. The problem we experienced is mentioned in the documentation as well: https://cmake.org/cmake/help/latest/policy/CMP0149.html#policy:CMP0149

In essence, the version of Windows that CMake was running on was potentially anchoring the SDK to an old version. This is more likely to be an issue on Windows Server than it is on Windows 10/11.
