### ISSUE TITLE
[question] how to use conan source with ALL Setup?

### ISSUE THREAD

**Issue by Talkless** [conan-io/conan-center-index#133]
Running `conan . source -sf=source` within `recipes/openssl/ALL` gives this error:
```
$ conan source . -sf=source
[HOOK - conan-center.py] pre_source(): [IMMUTABLE SOURCES (KB-H010)] OK
conanfile.py (openssl/None): Configuring sources in /home/vincas/code/opensource/conan/conan-center-index/recipes/openssl/ALL/source
conanfile.py (openssl/None): Executing exports to: /home/vincas/code/opensource/conan/conan-center-index/recipes/openssl/ALL/source
conanfile.py (openssl/None) exports: File 'conandata.yml' found. Exporting it...
conanfile.py (openssl/None) exports: Copied 1 '.yml' file: conandata.yml
ERROR: conanfile.py (openssl/None): Error in source() method, line 115
        tools.get(**self.conan_data["sources"][self.version])
        KeyError: Non
```
How do I get source of, let's say, OpenSSL 1.0.0s? Or more general question, how to use [Package development flow](https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html) with this kind of setup?

Thanks!

**Comment by Minimonium** [comment]
Hi, Vincas.

The `openssl` recipe doesn't explicitly set the `version` attribute, but depends on it in the `source()` function. To provide that information you should pass the `--install-folder` argument built with explicit version (e.g. `conan install . openssl/1.0.2@`). 
https://docs.conan.io/en/latest/reference/commands/development/source.html

A small note, I'd generally advice against using the Development Flow anywhere outside of testing the specific recipe due to numerous problems with it.

**Comment by Talkless** [comment]
Thanks @Minimonium , it did the trick!

Yes, I want to use Development Flow only for developing (improving) profile.
