### ISSUE TITLE
[question] Where is Eigen3Config.cmake?

### ISSUE THREAD

**Issue by jpfeuffer** [conan-io/conan-center-index#13353]
Hi. I am using conan with the cmake_paths generator.

When it downloads Eigen3 (3.4) however, my `find_package(Eigen3)` call with `cmake -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake ...` fails because it cannot find the Eigen3Config.cmake.

When I build Eigen3 myself, the config installs correctly.

**Comment by jpfeuffer** [comment]
I was checking ` /root/.conan/data/eigen/3.4.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/` and it is just not there

**Comment by mzukovec** [comment]
All conan center recipes remove `cmake` files that are generated by the library because there would be interference with some of the conan generators. Instead of `cmake_paths`, you should use `cmake_find_package` for `find_package(Eigen3) ` and `cmake_find_package_multi` for `find_package(Eigen3 Config) `. Don't forget to se the `CMAKE_MODULE_PATH` or `CMAKE_PREFIX_PATH` accordingly.

You can read more about available generators here:
https://docs.conan.io/en/1.53/integrations/build_system/cmake.html

**Comment by jwillikers** [comment]
@jpfeuffer Conan will generate `Eigen3Config.cmake` for you. You need to use the appropriate CMake generator, with CMakeToolchain and CMakeDeps being the recommended ones. The file will appear in the build directory, possibly in the `generators` directory if you specify a layout for your project. The CMakeToolchain generator will point your project to the Conan-generated CMake modules.

**Comment by jpfeuffer** [comment]
Thanks a lot for your quick and helpful answers. Both cmake_find_package_multi and CMakeDeps worked!
I used CMakeDeps since cfpm cannot handle optional Components.

**Comment by uilianries** [comment]
@jpfeuffer cmake_find_package_multi will be deprecated on Conan 2.0, `CMakeDeps` will become the default one. There are recipes which still need to be updated, so not all packages are prepared to use CMakeDeps, but at some point we will used only it.

**Comment by prince-chrismc** [comment]
https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#why-are-cmake-findconfig-files-and-pkg-config-files-not-packaged

Needs some 2.0 updates but it's in the docs :)
