### ISSUE TITLE
[question] why do we use _create_cmake_module_alias_targets so much?

### ISSUE THREAD

**Issue by paulharris** [conan-io/conan-center-index#13550]
I see a lot of recipes that define their own _create_cmake_module_alias_targets(),
why is there no built-in conan function for this?
It seems like a hackish solution ...

I nearly forgot to mention, there is a note in szip's recipe:
```
        # TODO: to remove in conan v2 once cmake_find_package* generators removed
        self._create_cmake_module_alias_targets(
            os.path.join(self.package_folder, self._module_file_rel_path),
            {"szip-shared" if self.options.shared else "szip-static": "szip::szip"}
        )
```

szip only defines the target "szip-static" or "szip-shared", which is annoying.
I want it to also define an szip::szip modern target I can link to (and perhaps the old ones should die?),

So won't I still need a module-alias even after cmake_find_package* is removed?

And should this be something a v2-migration linter should check for?

**Comment by paulharris** [comment]
Note that I noticed this because the modern finders don't seem to be finding szip's alias for szip::szip

**Comment by uilianries** [comment]
Good question. 

@paulharris It's a Conan V1 limitation and should removed in the future as soon as `cmake_find_package` and `cmake_find_package_multi` become deprecated and removed from CCI.

As you should noted, those new properties in cpp_info are much better and should replace it.

About an internal feature, Conan client will not invest time "fixing" something which is already timed to be deprecated. Instead, Conan will prefer investing time improving Conan 2.0.

It smells, but will continue present for some time.

**Comment by paulharris** [comment]
Ok, so how best to create an alias (or duplicates, or just copy-pastes) in this case:
https://github.com/conan-io/conan-center-index/pull/13551

I've used components before, but components["szip-static"] will give me szip::szip-static ... right?

**Comment by jcar87** [comment]
Answering generically without knowing the specifics of `szip`:

I believe some effort has been made to move towards recipes in ConanCenter providing target names _as they would be_ provided by the upstream equivalent. The legacy Conan cmake generators would have provided targets like `CONAN_PKG::xxx` or similar. While having the convenience is there, this means that consumers who want to integrate Conan have to make "invasive" changes to their existing build scripts. Whereas the newer `CMakeToolchain` + `CMakeDeps` can provide an almost transparent integration, by means of configuring the consumer project with `-DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake`, without having to make any further changes in the existing scripts.

If the upstream `szip` does _not_ provide an `szip::szip` target named as such, but rather one of `szip-static` and `szip-shared`, this leaves us in unfortunate position. One may be tempted to tweak the recipe to provide something more readily adapted to modern conventions, like `szip::szip`, but this introduces the risk of the recipe being the "first" to follow that convention for the particular library, which carries the risk of bringing us back to square one: somebody somewhere will have to modify their CMakeLists.txt in order to consume the recipe from ConanCenter. 
 
 This carries particular risk when there are other open source libraries that we also host in ConanCenter, and the build scripts for those already reference the pre-existing upstream names - then those recipes would have to patch their CMake scripts in order to consume the recipe. I believe this is the motivation behind the `_create_cmake_module_alias_targets()` function: have it in such a way that the recipe provides the target names with the pre-existing convention, but also provide a more modern one. While still suboptimal, it minimises the chance of anyone having to patch or alter a CMakeLists just to consume the library.

**Comment by paulharris** [comment]
Yes I think I get all of that,
the problem was the alias_targets seemed to only work for old finders, not my new modern consuming recipe.

So I'm wondering if there is an example or template that I can copy that does what I need ...
It seems to be a common problem at the moment, so I think a template of how it should be done best would be good.

**Comment by SpaceIm** [comment]
> the problem was the alias_targets seemed to only work for old finders, not my new modern consuming recipe.

It's the opposite

**Comment by prince-chrismc** [comment]
> but follow what has been defined upstream if an

Always follow upstream 👍

**Comment by prince-chrismc** [comment]
As for the solution the 2.0 properties dont make the same assumptions as the old one, so you should be able to just stick the correct one in  as Space pointed out 

A very quick check pulled a lot of examples, here's one

https://github.com/conan-io/conan-center-index/blob/ca38b0f664c0348b30b9e68df93e58c96d428ba6/recipes/asyncplusplus/all/conanfile.py#L86

**Comment by SpaceIm** [comment]
AFAIK there is nothing to change in package_info() of szip recipe.

**Comment by paulharris** [comment]
Ok, so the ONLY reason that szip::szip was defined in the past was due to some conan v1 limitation which is going away?

And so in the future, the consumers of this recipe will continue to link like the test_package does, like so:
```
if(TARGET szip-shared)
    target_link_libraries(${PROJECT_NAME} szip-shared)
else()
    target_link_libraries(${PROJECT_NAME} szip-static)
endif()
```

Correct?

**Comment by SpaceIm** [comment]
Yes

**Comment by paulharris** [comment]
Thanks!
