### ISSUE TITLE
[question] CMakeToolchain and cmake_minimum_required

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan-center-index#13671]
CMakeToolchain currently requires CMake to be at least 3.15
https://github.com/conan-io/conan/blob/e8ea2bacba65a46a50b1aada92c538a488006862/conan/tools/cmake/toolchain/toolchain.py#L93

But even package templates in CCI have much lower version. Is this intended?

**Comment by SpaceIm** [comment]
It doesn't really matter. CCI recipes have cmake_minimum_required in their CMakeLists adjusted to features they are using internally, not what conan toolchain requires, because conan toolchain is designed to work regardless of cmake_minimum_required of CMakeLists.

**Comment by prince-chrismc** [comment]
🤔 looking at https://github.com/conan-io/conan-center-index/blob/d348c438f13c7e5828d8eb73cd8bf9c21f0cd712/docs/package_templates/cmake_package/all/test_package/CMakeLists.txt I think it's just copy pasted.

The C++ 17 requirement needs 3.8 so that was probably already there and just wast not changed.

Feel free to open a PR fixing them :) Since they are a point of reference they should be consistent

**Comment by AndreyMlashkin** [comment]
relates to https://github.com/conan-io/conan/issues/12143

Maybe it's already time?

**Comment by SpaceIm** [comment]
Not really
