### ISSUE TITLE
[question] Disable V2 linter

### ISSUE THREAD

**Issue by HappySeaFox** [conan-io/conan-center-index#14927]
### What is your question?

Hi. Previously I could disable V2 linter, but now it seems impossible to do. Is there other way to disable it, or re-enable this possibility to disable linter for limited use-case like bugs in conan?

Why do I need this? My recipe (https://github.com/conan-io/conan-center-index/pull/14871) is blocked by one of it since September (https://github.com/conan-io/conan-center-index/pull/13000, https://github.com/conan-io/conan-center-index/issues/13159), and now I realized that there is another one in `CMakeDeps` (https://github.com/conan-io/conan/pull/12600) that could possibly block it for a few months more. I'd like to just update the version of my recipe and leave it V1-compliant only. V2 migration could be done later.

**Comment by SpaceIm** [comment]
Current v2 linter doesn't enforce full conan v2 migration. You can keep old build helpers & generators for the moment (conans.tools.CMake class, cmake & cmake_find_package generators), and only translate few legacy functions to copy, get, rmdir, rm etc

**Comment by uilianries** [comment]
Hello and Merry Christmas @HappySeaFox! Indeed is not possible to disable the linter and it can be boring in some cases. Unfortunately, we would not be able to find a git diff to integrate to the linter, to check if it's a bump version only and avoid the linter. 

There is a hooks which checks when someone tries to disable pylint: https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#kb-h072-pylint-execution

Plus, there is a good reference about those new tools to be used instead of the legacy one: https://github.com/conan-io/conan-center-index/blob/master/docs/v2_linter.md

Like SpaceIm said, most of errors you just need to replace some imports.

**Comment by HappySeaFox** [comment]
Thanks!
