### ISSUE TITLE
[question] Correct way to conditionally depend on `libjpeg-turbo` or `libjpeg`

### ISSUE THREAD

**Issue by HappySeaFox** [conan-io/conan-center-index#14951]
### What is your question?

Hi. I'm trying to add an option in my recipe to enable JPEG. The option has three possible values: `libjpeg-turbo`, `libjpeg`, and `False`. I tried to implement the similar approach as other recipes (`freeimage`) do and enabled the `libjpeg-turbo` value be default in `default_options`:

```
    options = {
        ...
        "with_jpeg": ["libjpeg", "libjpeg-turbo", False],
    }
    default_options = {
        ...
        "with_jpeg": "libjpeg-turbo",
    }
    def requirements(self):
        ...
        if self.options.with_jpeg == "libjpeg-turbo":
            self.requires("libjpeg-turbo/2.1.4")
        elif self.options.with_jpeg == "libjpeg":
            self.requires("libjpeg/9e")
```

 But the PR https://github.com/conan-io/conan-center-index/pull/14926 fails with:

```
ERROR: At least two recipes provides the same functionality:
 - 'libjpeg' provided by 'libjpeg-turbo/2.1.4', 'libjpeg/9e'
```

Am I missing anything? Any ideas?

**Comment by HappySeaFox** [comment]
It seems that the problem is that if one of my dependencies depends on `libjpeg`, but I explicitly ask to enable `libjpeg-turbo` for my recipe, there is a conflict between those two. Like that: 
```
sail -> tiff -> libjpeg
   |
   v
libjpeg-turbo 
```

Is there a way to workaround that?

**Comment by SpaceIm** [comment]
to change to libjpeg? It's the current default implementation of all CCI recipes. I don't say it's a good default.

Once https://github.com/conan-io/conan-center-index/pull/14814 will be merged, we'll be able to rely on this virtual recipe and globally delegate libjpeg implementation in this recipe instead of scattering this decision to many recipes with high risk of conflicts.
