### ISSUE TITLE
[question] Download prebuild package

### ISSUE THREAD

**Issue by artkuli** [conan-io/conan-center-index#15294]
Hi,
I would like to ask about downloading prebuild packages from ConanCenter. As I understand it, when I create a PR with adding my package to the repository. The package will be available to Conan users who will be able to install the package by: `conan install mypackage/version`.
If I include the archived source code in the recipe, will CI build the project for the most common platforms and the end user will have access to the compiled version of the package, or will the end user have to compile the package themselves?
After reading the article:  https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/README.md#the-build-service I understand that package will be created by ConanCenter build system directly, but I would like to make sure 😊

**Comment by SpaceIm** [comment]
Hi

Users have to compile from source if their settings don't match https://github.com/conan-io/conan-center-index/blob/master/docs/supported_platforms_and_configurations.md.
The default behavior of `conan install` is to download pre-build packages, and raise an error if there is no pre-built package.
With `conan install -b missing`, pre-built package is downloaded from conancenter remote if available, otherwise it builds from source locally by downloading source code and building with whatever steps defined in the recipe.

**Comment by artkuli** [comment]
Hi @SpaceIm,
Thank for you quick response. 
So I understand, if user has settings which don't match with supported platforms and configuration then they have to build package by themselves.

**Comment by SpaceIm** [comment]
> So I understand, if user has settings which don't match with supported platforms and configuration then they have to build package by themselves.

Yes, and it's done automatically for the all dependency graph is they pass `-b missing` while calling `conan install` or `conan create`.
Actually it's not conan-center specific, it's how conan client works when interacting with a conan remote. What is specific to conan-center remote is the list of settings for which there are pre-built packages (basically major desktop OS & compilers for the moment).
Private conan remotes may want to store pre-built packages of other settings suitable to their needs (they may even want to store source code of all external libraires in their own artifactory, and fork conan-center recipes so that their forked recipes can work in full isolation).

**Comment by artkuli** [comment]
Great! I got it.
Additional question, who is responsible for keeping the package version up-to-date? Maintainer who add this package to conan center?

**Comment by SpaceIm** [comment]
Anybody who wants to contribute to conan-center. You can submit a PR to add a new recipe, fix a recipe or add a new version. These PR are reviewed by conan team (employees of JFrog) and community reviewers (not employees of JFrog), and merged automatically if they pass CI tests and get at least 2 approvals (with at least one approval from conan team). There are roughly 10 PR merged every day, sometimes far more.

**Comment by artkuli** [comment]
Thank you a lot for the replies. I got all information which I need :)
Close the ticket
