### ISSUE TITLE
[question] Assimp: use conan recipes instead of internal contribs?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#1576]
Assimp does not only depends on `zlib` (with `minizip`, which is not listed in the recipe, there are probably link issues for some specifics options, I'm surprised that linking even works when producing the shared lib) and `irrxml`, but also:
- `utfcpp`
- `zip` (only for 3MF Exporter, but Assimp compile or link it unconditionally): https://github.com/kuba--/zip
- `rapidjson` (only for glTF and glTF2, but Assimp compile or link it unconditionally)
- `poly2tri`: https://github.com/jhasse/poly2tri
- `openddlparser`: https://github.com/kimkulling/openddl-parser
- `polyclipping`: https://sourceforge.net/projects/polyclipping
- (also `Open3DGC` but I don't know if the similar "version" than Assimp one could be packaged, doesn't seem to have a dedicated repo)

In CMakeLists files, it has a logic to use external libs if `HUNTER_ENABLED` is `ON`, and a custom hunter function. With few modifications, it could work without Hunter.

**Comment by SSE4** [comment]
we always must use external (conan) library, at least by default.
the reason is that way it's easy to get ODR violations - you may easily have two instances of zlib, one from conan itself, and one from the assimp. it's also likely they could be different versions of the same library.
in that case, you'll probably get strange runtime errors hard to debug.

the plan should be:
- package all mandatory dependencies first
- in recipe, ensure that internal copies of libraries aren't used. the most reliable way is to remove `3rd-party` directory and set corresponding build system flags/options
- potentially, you may give an option to use internal dependency, but it's strongly discouraged

**Comment by SpaceIm** [comment]
I totallly agree @SSE4, it was not really a question actually, more a suggestion. But this issue doesn't really fit Bug Report template 😃

**Comment by SpaceIm** [comment]
https://github.com/conan-io/conan-center-index/issues/1576
