### ISSUE TITLE
[service] Build packages for GCC 10

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan-center-index#1587]
Now where https://github.com/conan-io/conan-docker-tools/pull/199 is merged, the service should generate packages for GCC 10.

If added, the wiki should be updated as well: https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations

**Comment by danimtb** [comment]
We are working in the backend in order to be able to rebuild packages whenever it is needed. Of course that work includes generating packages for new compilers. Currently we cannot commit to a deadline for this but it is high in our priority list. You can check https://github.com/conan-io/conan-center-index/projects/1#card-41086361 to see the ongoing work

**Comment by madebr** [comment]
What is the progress on this?
- gcc 10.1 had been released on 2020-05-07
- gcc 10.2 has been released on 2020-07-23
- ...

**Comment by sachnk** [comment]
Any updates on this?

**Comment by madebr** [comment]
@jgsogo @danimtb 

Is there any update on this?
Is there a process in place to do a complete rebuild?

**Comment by jgsogo** [comment]
Hi! We are already generating binaries (in the backend) for GCC 10 (also apple-clang 12.0 and new versions of clang).

```
conan search zlib/1.2.11@ --table=zlib.html -r conan-center
```

![image](https://user-images.githubusercontent.com/1406456/100986223-33a2e700-354d-11eb-8844-a67d9ebd2b05.png)

The job takes all the latest revision of every recipe in order and check for missing configurations (these new compilers are missing configurations) and build them. It takes too much time. The problem is: while this job is running new PRs without these new configurations are being merged and there are new revisions... We need to think how and when to start generating these new revisions for PRs, we might get some errors saying that there are missing dependencies (because of a new revision of one of the requirements without the new configurations), or maybe we add a mark to PRs that will tell the CI to generate all the configurations, some power-users can add this mark and they know what to do if there are missing dependencies (notify and we will force those missing deps in the backend).

Next steps:
 * design this _migration_ process with the team
 * fix all the recipes that are failing due to hooks (I will open some PRs like I did the week before 😅 )
 * keep generating binaries <-- improve/parallelize this job so it goes much faster
    + identify recipes that are failing with these new configurations (I've seen some failure, very few, but I haven't entered the logs, I cannot tell the reason).
 * implement the migration plan

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/4636

Thanks!
