### ISSUE TITLE
[question] Submitting PR v.s. "Include My Package" on Bintray

### ISSUE THREAD

**Issue by hnOsmium0001** [conan-io/conan-center-index#1681]
I understand that both the README.md and the wiki states very clearly that
1. This repo is the default package source for Conan
2. This repo simplifies package publishing steps (especially for older libraries that doesn't want to support Conan directly) by having a building service

But I don't think there is a clear guideline for newer packages where the author wants the package to be on Conan. Should the author spent effort maintaining a fork of CCI? Or should they just create a personal Conan repository on Bintray, and use the "Include My Package" function?

**Comment by uilianries** [comment]
Hi!

> But I don't think there is a clear guideline for newer packages where the author wants the package to be on Conan.

There is a [blog post](https://blog.conan.io/2019/09/04/A-new-binary-building-service-for-Conan-center-packages.html) about Conan Center Index which explains that CCI is the better/easier for distribution.

> Should the author spent effort maintaining a fork of CCI? Or should they just create a personal Conan repository on Bintray, and use the "Include My Package" function?

As described on the post, CCI is the more natural way. Personal Bintray repository are useful for the cases where a package will not be accepted in CCI (big complex and modular packages, or pre-built installers), or for companies which want to distribute their packages as a product. Otherwise CCI, is the best choice.

**Comment by hnOsmium0001** [comment]
Thank you for clarification, I think the last part in your response isn't made very clear in the blog post, and it's why I was here.
