### ISSUE TITLE
[question] ninja package still broken?

### ISSUE THREAD

**Issue by tbsuht** [conan-io/conan-center-index#17390]
### What is your question?

Hi,

this regeneration of the ninja package did not fix the problem, at least I experience that: https://github.com/conan-io/conan-center-index/pull/17135

I need to rebuild the ninja package locally to have a usable package. (for conan 2.x)

Can someone confirm this?

**Comment by ericLemanissier** [comment]
On my end the problem is fixed. Can you try with a clean conan cache (`rm -r ~/.conan2/p`) or add `-u` argument to your conan command so that it updates your local cache.

**Comment by tbsuht** [comment]
@RubenRBS Pinging as suggested in the last PR: https://github.com/conan-io/conan-center-index/pull/17135#issuecomment-1521334379

**Comment by RubenRBS** [comment]
Taking a look now, thanks for the heads up :)

**Comment by RubenRBS** [comment]
Sorry for the radio silence, work is ongoing on addressing this issue, but we have had to prioritize other things first

**Comment by jcar87** [comment]
Hi @tbsuht  - thanks for reporting this, and @ericLemanissier  for providing additional details.

If the error you were getting when running `ninja` had to do with `GLIBCXX` symbols, I believe this should now be fixed. If you could try again and let us know, that would be great! 


For context - `ninja` is built from C++ code, and on Linux for Conan 2.0 we are building with gcc 11 - this imposes a requirement on the running system, where a `libstdc++` is required that contains symbols with for `GLIBCXX_3.4.29` (matches gcc11 which is what the ninja binaries are currently generated with for Conan 2.0) - as per GCC's ABI guidelines: https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html. I suspect on some systems it is possible to install a newer runtime without issues, but this is not a burden we would like to impose on our users.

This should now be resolved since https://github.com/conan-io/conan-center-index/pull/17620 by statically linking the C++ runtime
