### ISSUE TITLE
[package] All debug MSVC packages miss debug information aka PDB's

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#1741]
I'm currently trying to track a bug/crash/feature/my-own-fault originating in the systemc package.
Debugging on MSVC can be done using debug information [built-in or external PDB's (/Z7 vs /Zi)](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=vs-2019).
The Debug MSVC packages currently do not contain this information.
This means the debug packages do not provide any extra convenience (apart from some extra assertions).

To track the code flow inside the systemc library,
I will have to modify the systemc library to also package the pdb file in debug mode.
I don't think this is the supposed way.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **all/all**
  * Operating System+version: **Windows**
  * Compiler+version: **Visual Studio**
  * Docker image: *n/a*
  * Conan version: **conan 1.25.2**
  * Python version: **Python 3.8.3**

**Comment by jeremy-coulon** [comment]
I agree with @madebr .
I mostly use Debug/RelWithDebInfo build types.
Unfortunately I had to change almost all recipes that I use in order to have pdb symbols.

I understand that pdb consumes a lot of disk space and that conan-center-index may be limited by that. It this is the only reason, then I believe that it would be better if conan-center-index only provided Release pre-built binaries and users could add `--build missing` when they needed another build type.

**Comment by madebr** [comment]
Closing this one. See  #1982
