### ISSUE TITLE
gtest/1.8.1 not conan 2.0 compliant

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan-center-index#17949]
### Description

The recipes looks for compiler "Visual Studio" which does not exist in conan 2.0
Recipe line 187.

I have no suggestion for a fix as I am not a Visual Studio expert

Regards
Klaus

### Package and Environment Details

OS: WSL Ubuntu 22.04
Conan: 2.0.0
recipe: gtest/1.8.1
rrev: aa85cb80d8f4b63cf79905881965fc96

### Conan profile

none

### Steps to reproduce

none

### Logs

none

**Comment by toge** [comment]
@klausholstjacobsen 
Thank you for your report.
This problem is due to dropping support for versions prior to gtest/1.12.0 on 2022-Sep.
https://github.com/conan-io/conan-center-index/pull/13049

As for gtest/1.10.0, it is now supported again and can be used with conan v2 without any problems.
https://github.com/conan-io/conan-center-index/pull/13833

Please consider using gtest/1.10.0.

If gtest/1.8.0 is mandatory, it may be merged if you create a PR that again supports 1.8.0.

However, there seem to be certain criteria for adding older versions.
https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/sources_and_patches.md#adding-old-versions

**Comment by klausholstjacobsen** [comment]
Takuya, Thanks a lot.

I will have a look at writing a contributing patch.
The reason for using gtest 1.8.1 specifically is because it is the latest version supported by QNX 7.0 which is one of my target platforms.

//Klaus
