### ISSUE TITLE
[conan.io/center] Package highs 1.5.3 missing although recipe exists

### ISSUE THREAD

**Issue by hedtke** [conan-io/conan-center-index#18468]
### What is your problem/feature request?

highs is available in version 1.5.3: https://github.com/conan-io/conan-center-index/blob/master/recipes/highs/config.yml but it is not shown in conan center

**Comment by jcar87** [comment]
Hi @hedtke - thank you for reporting this.

I can see that there are binaries available for this reference, both with Conan 1.x:

```
conan search highs/1.5.3@ -r conancenter
```

and with Conan 2.0:
```
conan list "highs/1.5.3:*#*" -r conancenter
```

is this not the case?

**Comment by hedtke** [comment]
the website lists only 1.4.2: https://conan.io/center/highs

**Comment by jcar87** [comment]
Hi @hedtke  - apologies. We are currently working on updating the website and the information may not be up-to-date.

**Comment by hedtke** [comment]
@jcar87 we experienced some minor issues with Conan in the past: stuck pipelines, website issues etc... I don't want to blame anybody, I want to help. How can we help? Anything I can do personally or my company an do? Provide servers, donate ...?

**Comment by jcar87** [comment]
Hi @hedtke, thank you for your message. The best way to support the project is to continue raising issues like this, as it helps us direct our attention to where is needed to continue improving the user experience. Since the Conan 2.0 launch, we have focused our efforts towards making sure we continue the efforts of migrating all recipes in Conan Center to be compatible with Conan 2.0 - today we estimate 80% of all recipes, including the most used ones, are compatible and have published binaries. We are currently working on a refresh of the Conan Center website that uses Conan 2.0 features with a refreshed backend architecture, which should be more reliable to these minor issues that you are mentioning. With the help and feedback of users like yourself we will continue addressing these issues to provide a better experience.

**Comment by hedtke** [comment]
Highs is now listed on the new version of the website
