### ISSUE TITLE
[package] glib/*: Error: duplicate definition of variable 'bindir'

### ISSUE THREAD

**Issue by valgur** [conan-io/conan-center-index#18604]
### Description

I'm not too familiar with Meson, so I'm not sure what the correct way to handle this error should be. Commenting out https://github.com/conan-io/conan-center-index/blob/07ebcf40e/recipes/glib/all/conanfile.py#L262 fixes the build at least.

@SpaceIm do you have any ideas?

### Package and Environment Details

* Package Name/Version: **glib/2.76.3**
* Operating System+version: **Linux Ubuntu 20.04**
* Compiler+version: **GCC 11**
* Conan version: **conan 2.0.7**
* Python version: **Python 3.8.10**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

### Steps to reproduce

conan create . --version 2.76.3

### Logs

<details><summary>Click to expand log</summary>

```
ERROR: glib/2.76.3 (test package): Error in test() method, line 58
	gdbus_codegen = pkg_config.variables["gdbus_codegen"]
	ConanException: Command 'pkg-config --print-variables gio-2.0 --print-errors' failed with errorcode '1'
b"Duplicate definition of variable 'bindir' in '/home/martin/projects/conan-center-index/recipes/glib/all/test_package/build/gcc-11-x86_64-20-release/generators/gio-2.0.pc'\n"
Command exited with non-zero status 1
```

</details>

**Comment by SpaceIm** [comment]
I guess it's a side effect of https://github.com/conan-io/conan/pull/13623 (conan 2.0.7). glib recipe has a workaround to define bindir in .pc file generated by PkgConfigDeps, but since https://github.com/conan-io/conan/pull/13623 this bindir is also defined so it might lead to your error.
So the fix would be to define bindir in pc files of glib recipe only if conan_version < 2.0.7, for these 2 lines:
https://github.com/conan-io/conan-center-index/blob/07ebcf40e03aa49e251c59f86789cb63aaaeb62d/recipes/glib/all/conanfile.py#L262
https://github.com/conan-io/conan-center-index/blob/07ebcf40e03aa49e251c59f86789cb63aaaeb62d/recipes/glib/all/conanfile.py#L279

**Comment by valgur** [comment]
Thank you very much, @SpaceIm! That appears to have been the cause, indeed.

The good news is that it no longer fails after upgrading to v2.0.8, so this issue can be closed.
