### ISSUE TITLE
[question] Architectures other than x86_64

### ISSUE THREAD

**Issue by db4** [conan-io/conan-center-index#1869]
Looks like conan center is not going to have binaries for anything other than `x86_64` anymore. What if I need them (say x86 and armv8) and don't like to rebuild the world for every workstation / CI job? What would you recommend to make them available locally? Forking conan-center-index repo and recreating all CI infrastructure for Travis CI/AppVeyor doesn't look a viable option.

**Comment by uilianries** [comment]
Hello @db4 !

> What if I need them (say x86 and armv8) and don't like to rebuild the world for every workstation / CI job? What would you recommend to make them available locally? Forking conan-center-index repo and recreating all CI infrastructure for Travis CI/AppVeyor doesn't look a viable option.

There are two important points:

- Few users require different packages which are not x86_64 platform, also, most of companies build their own packages, or because to avoid any security concern or for a specific profile which they need. 
- Each recipe results in ~130 packages, only for x86_64 and not all package are used. Now imagine adding more profiles which will be consumed by 1% of users, it's impracticable, because it would increase CCI storage and CI time for no usage.

We recommend you building your own required packages, I believe you don't need all packages in CCI, so build only what you need of avoid effort and time. You can use free CI services, like Travis, Appveyor, CircleCI, Github Actions, Azure or Gitlab.

Also, you can use Artifactory for local storage or even Bintray if you want to distribute globally.

There is another related issue:
- https://github.com/conan-io/conan-center-index/issues/537

For now, CCI only supports the follow configurations, and there is no idea for an update in short/middle term:
- https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations

**Comment by db4** [comment]
Hi @uilianries 
>There are two important points:
>
>-   Few users require different packages which are not x86_64 platform, also, most of companies build their own packages, or because to avoid any security concern or for a specific profile which they need.
>-  Each recipe results in ~130 packages, only for x86_64 and not all package are used. Now imagine adding more profiles which will be consumed by 1% of users, it's impracticable, because it would increase CCI storage and CI time for no usage.

I understand that. But conan-center provided Windows/x86 packages before and  we (my colleagues and me) used to rely on them. And I always thought that conan-center binaries can be trusted if one needs something very lommon like boost or gzip no matter for corporate or individual use. Now you recommend us to have all binaries locally. Ok, no problem, we have a local conan repo, CI infrastructure etc.  But how to make the process of building missing binaries as transparent as possible? Clone conan-center-index and add custom CI scripts, uploading the binaries to the local repo?

And another point. Building for x86_64 only means that package recipes are not tested w.r.t. other architectures (not even mentioning subtle issues that may raise during cross-compiling). That means the inevitable degradation of recipes quality.

**Comment by SSE4** [comment]
we don't build for all architectures, right now we only build for **x86_64**. it may change in future if there will be high demand for them. we also don't test all compilers, operation systems, etc., only the most popular. for other architectures:
- **x86** appears to be slowly dying, e.g. it's already deprecated on **macOS** and **Linux** distributive are also removing that
- **ARM** doesn't appear to be very frequently requested, but there are desktop systems moving to ARM (e.g. Apple might move their laptops to ARM in future, there are existing Android ARM laptops, etc.), so it might get more attention in the near feature
- **mips**, **PowerPC**, **Sparc** even less popular right now

but we still accept patches and fixes for other configurations, such as x86, ARM, Android, iOS, MinGW, FreeBSD, etc.

**Comment by db4** [comment]
@SSE4 I still think Windows/x86 is an exception. For me silently discarding its support is a major issue. You may not provide binaries for it - OK, it's understandable, you have limited server space, but you should run CI tests for it. Right now I trying to build protubuf 3.9.1 for Windows/x86, and (surpise!) it's broken! This shouldn't be a rule for conan-center packages.
