### ISSUE TITLE
[opencv] opencv/4.1.1: Building with GTK always fails silently on Ubuntu 20.04 because of GLib version

### ISSUE THREAD

**Issue by Cyberdr8gon** [conan-io/conan-center-index#1894]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **opencv/4.1.1**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.26.0**
  * Python version: **Python 3.8.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Attempt to build OpenCV package with contrib=True on Fresh Ubuntu 20.04. After installing necessary packages (such as libgtk-2.0), the build output suggests that the glib version is insufficient to build the package. Thus, this doesn't build on Ubuntu 20.04.

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
-- Checking for module 'gtk+-3.0'
--   Package 'pango' requires 'glib-2.0 >= 2.59.2' but version of glib-2.0 is 2.58.3
-- Checking for module 'gtk+-2.0'
--   Package 'pango' requires 'glib-2.0 >= 2.59.2' but version of glib-2.0 is 2.58.3
```

</details>

**Comment by uilianries** [comment]
Hi @Cyberdr8gon ! 

OpenCV is not yet ported to Conan Center Index, but you should do it in the future. It's part of Conan Community.

About your problem, each package uses a specific Ubuntu version to be built in the CI, which means it's linked to a specific glibc version. It seems like pango, which is a system package, requires a newer version of glibc. I think the best option would be packaging pango, because Conan doesn't filter the glibc version (it can be added as custom settings). As this situation is related to the distro, we can't do much here, it seems like be a limitation from the distro. I think it's checking on ubuntu launchpad to see if there is any report related to pango and glibc version.

**Comment by Croydon** [comment]
Pango -> https://github.com/conan-io/wishlist/issues/17

**Comment by perseoGI** [comment]
Hi there 👋 

I'm closing this issue as this problem should have been addressed.
If problem persists, do not hesitate to reopen this issue or create a new ticket!
Happy coding 🐸
