### ISSUE TITLE
[question] install vs create in automation

### ISSUE THREAD

**Issue by robert-shade** [conan-io/conan-center-index#19158]
### What is your question?

I'm planning on updating some of our automation for building internal packages.

I noticed in the logs that when conancenter builds a package it does it with a `conan install`.  Why is that used instead of `conan create`?

**Comment by danimtb** [comment]
Hello @robert-shade and thanks for your question.

Indeed, we are using `conan install ... --build <ref>` in order to build the packages in conan center 😄  That's a very detailed appreciation of yours!

Answering your question, there is no resulting difference for doing a `conan create` vs `conan install`, we do it that way because it is conveninet for our CI flow design as we follow these steps:
- `conan export` --> Recipe is exported to the cache to capture many checks done by the conan hooks.
- `conan inspect` --> We inspect the recipe to check for relevant options shared/header_only/fPIC, to generate the profiles to build packages later.
- `conan info`/`conan graph` --> We compute the different package ids (or any missing dependencies) for the recipe exported. This is the key step, because some profile configuration may result on an invalid package ID (due to recipe restrictions) or duplicated package ids (like header only packages generate the same package for all profiles).
- `conan install --build` --> Now that we know the profiles that generate the different packages and that the recipe is already in the conan cache, we create the packages.

This is the general flow we follow without providing too much detail. Take into account that we run the test package in a different step as well while `conan create` does it all with just one command (which is more convenient).

I hope that helps you clariry some points and to improve your internal automation on generating packages!
- ``

**Comment by robert-shade** [comment]
Very helpful, thanks!
