### ISSUE TITLE
[question] pkgconf + CMake

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan-center-index#19780]
### What is your question?

Hi.

Will it be useful to remove pkgconf build requirement for libraries that use CMake through additional patch? If I understand correctly, having normal find_package instead of pkg_check_modules should work perfectly fine for requirements that are provided by conan.

Or is it better to have this mix of pkg_check_modules with find_package?

**Comment by SpaceIm** [comment]
There is not rule. If upstream CMakeLists relies on pkgconf for the discovery of few libraries, then I don't see any reason to patch this file forever unless there is a good reason or if it leads to an improvement of build robustness.

**Comment by Nekto89** [comment]
> There is not rule. If upstream CMakeLists relies on pkgconf for the discovery of few libraries, then I don't see any reason to patch this file forever (maintenance burden) unless there is a good reason or if it leads to an improvement of build robustness.

pkgconf is additional build requirement. And pkgconf requires meson. And meson requires ninja.
I just looked at minizip-ng recipe and CMakeLists.txt and it looks like it should be quite easy to get rid of it.

**Comment by SpaceIm** [comment]
> I don't fully understand what pkgconf brings to the table in case of using conan.

It depends. But if upstream CMakeLists relies on pkgconf, you have to patch this file forever, it can be complex, and contributors tend to make mistake when then package new versions (patch may need to be updated for this new version).

For minizip-ng, patch may be quite simple, but a naive contributor may forget to propagate this patch to a new version, and it could work actually in some circumstances, but it may lead to side effects when pkgconfig is installed at system level (because minizip-ng first checks pkgconf before CMake config files).
