### ISSUE TITLE
[question] What is the proper usage of no_copy_source?

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan-center-index#21731]
### What is your question?

Hi,

When should "no_copy_source" attribute be used in packages? In templates I see it in "header_only" example, but there is no usage in "cmake_package". I thought that it should be used when there are no patches but I see "no_copy_source" in boost recipe which has a lot of patches.

**Comment by uilianries** [comment]
@Nekto89 nice question.

As the documentation about [no-copy-source](https://docs.conan.io/2/reference/conanfile/attributes.html#no-copy-source) says, it's related to package with a large code base, like Boost and Qt. These packages require many MB for each copy to the build folder, so it optimizes the used storage. 

It can use be used in ConanCenterIndex for any package, since it requires tons of bytes when downloading, or, its sources is the same that is present in the package folder (e.g. header only and pre-built executables).

**Comment by Nekto89** [comment]
> @Nekto89 nice question.
> 
> As the documentation about [no-copy-source](https://docs.conan.io/2/reference/conanfile/attributes.html#no-copy-source) says, it's related to package with a large code base, like Boost and Qt. These packages require many MB for each copy to the build folder, so it optimizes the used storage.
> 
> It can use be used in ConanCenterIndex for any package, since it requires tons of bytes when downloading, or, its sources is the same that is present in the package folder (e.g. header only and pre-built executables).

Documentation states "If you activate no_copy_source=True, it is mandatory that **the source code must not be modified at all by the configure or build scripts**, as the source code will be shared among all builds.". Does boost recipe break this rule for performance?
