### ISSUE TITLE
[request] aws-crt-cpp/latest

### ISSUE THREAD

**Issue by gocarlos** [conan-io/conan-center-index#2275]
### Package Details
  * Package Name/Version: **aws-crt-cpp/3.15.3**
  * Website: **https://github.com/awslabs/aws-crt-cpp**
  * Source code: **https://github.com/awslabs/aws-crt-cpp**

depends on: 
* [x] aws-c-common: Cross-platform primitives and data structures.
* [ ] aws-c-io: Cross-platform event-loops, non-blocking I/O, and TLS implementations.
* [ ] aws-c-mqtt: MQTT client.
* [ ] aws-c-auth: Auth signers such as Aws-auth sigv4
* [ ] aws-c-http: HTTP 1.1 client, and websockets (H2 coming soon)
* [x] aws-checksums: Cross-Platform HW accelerated CRC32c and CRC32 with fallback to efficient SW implementations.
* [x] aws-c-event-stream: C99 implementation of the vnd.amazon.event-stream content-type.

### Description Of The Library / Tool

C++ wrapper around the aws-c-* libraries. Provides Cross-Platform Transport Protocols and SSL/TLS implementations for C++.

cc/ @madebr as you did the previous job porting the aws C common libs

**Comment by st9007a** [comment]
I was trying to use Conan to manage my side project and found the latest version `aws-crt-cpp` in conan center is 0.18.8. Comparing with the latest version in AWS official, 0.26.1, it's a bit out of dated. So, I'd like to pick up this issue and try to update `aws-crt-cpp` to the latest version as well as its all aws crt dependencies. 

I plan to update the following packages to the version depended on by `aws-crt-cpp/0.26.1`. The order of these packages are following the dependency graph of aws crt libraries: https://docs.aws.amazon.com/zh_tw/sdkref/latest/guide/common-runtime.html

- [ ] aws-c-common: 0.9.12
- [ ] aws-lc: 1.19.0
- [x] aws-c-compression: 0.2.17
- [ ] aws-c-sdkutils: 0.1.13
- [x] s2n: 1.4.1
- [x] aws-c-cal: 0.6.9
- [ ] aws-c-io: 0.14.1
- [ ] aws-c-http: 0.8.0
- [x] aws-checksums: 0.1.17
- [ ] aws-c-auth: 0.7.10
- [x] aws-c-mqtt: 0.10.1
- [ ] aws-c-s3: 0.4.9
- [ ] aws-c-event-stream: 0.4.0
- [ ] aws-crt-cpp: 0.26.1

**Comment by perseoGI** [comment]
Hi @gocarlos, 

Thank you for reaching out to us!

I'm closing this issue because the latest version of `aws-crt-cpp` available in CCI is `v0.26.9` (see https://conan.io/center/recipes/aws-crt-cpp?version=0.26.9).

Currently, the latest tag upstream is `v0.29.6` (see https://github.com/awslabs/aws-crt-cpp/releases/tag/v0.29.6). Adding new versions of `aws-packages` in CCI can be complex due to the strict and fixed requirements between AWS packages. 

If you need the latest version, we welcome contributions! Alternatively, you can open a new ticket to request the specific version you need.

Happy coding! 🐸
