### ISSUE TITLE
[package] xz_utils/5.4.5 compromised

### ISSUE THREAD

**Issue by gouriano** [conan-io/conan-center-index#23326]
### Description

I get problem building xz_utils/5.4.5
https://conan.io/center/recipes/xz_utils?version=5.4.5
A closer look shows that when I download the source code:
wget https://tukaani.org/xz/xz-5.4.5.tar.xz
I get some HTML document instead.
(I did not risk to open that in a web browser)

### Package and Environment Details

* Package Name/Version: **xz_utils/5.4.5**
* Operating System+version: **Linux**

### Conan profile

Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux
[conf]

### Steps to reproduce

wget https://tukaani.org/xz/xz-5.4.5.tar.xz

### Logs

$ head xz-5.4.5.tar.xz 

\<!DOCTYPE html\>
\<html
  lang="en"
  
  data-color-mode="auto" data-light-theme="light" data-dark-theme="dark"
  data-a11y-animated-images="system" data-a11y-link-underlines="true"```
Put your log output here
```

**Comment by uilianries** [comment]
@gouriano The link mentioned redirects to Github, but the project is no longer available due the security breach reported last week: https://www.openwall.com/lists/oss-security/2024/03/29/4

To ConanCenterIndex CI, it should not be a problem, because we use [backup sources](https://docs.conan.io/2/devops/backup_sources/sources_backup.html) feature. However, for users it's not the same case.

I'll check with Conan team for a possible solution. Thank you for reporting.

**Comment by gouriano** [comment]
I was able to make it work with the Conan Center backup. Thank you.
