### ISSUE TITLE
[question] why does cpr package require gcc 9?

### ISSUE THREAD

**Issue by saukijan** [conan-io/conan-center-index#23563]
### What is your question?

Hi everyone! 

I was trying to use [cpr](https://github.com/conan-io/conan-center-index/blob/master/recipes/cpr/all/conanfile.py) package on debian buster, but I could not get it to compile due to [GCC version requirement](https://github.com/conan-io/conan-center-index/blob/master/recipes/cpr/all/conanfile.py#L47) being set too high. 

I was wondering if this is necessary because [cpr github page](https://github.com/libcpr/cpr?tab=readme-ov-file#requirements)  does not specify the minimum GCC version. Also, I managed to get it to compile and run by manually changing [minimum GCC version](https://github.com/conan-io/conan-center-index/blob/master/recipes/cpr/all/conanfile.py#L47) to 8. 

My test setup is: 
**os version**: Debian 10 (Buster)
**gcc version:** 8.3.0 (Debian 8.3.0-6)
**cmake version:** 3.26.3
**conan version:** 2.2.2

**Comment by Ahajha** [comment]
Looks like the restriction was added for version 1.10.0 here: https://github.com/conan-io/conan-center-index/pull/15522/files, specifically this commit: https://github.com/conan-io/conan-center-index/pull/15522/commits/21da396a8f09d82d366c07e5b4827fd23b6e24c4

GCC 8 does support C++17, and 1.10.0 requires C++17, so I suppose it would make sense that it should work. I suppose it was just a minor oversight.

Just note that CCI (last I checked) currently doesn't test GCC 8, only 5, 7, 9, and 11, so it won't get tested in CI.

**Comment by Ahajha** [comment]
@saukijan I think the policy is that so long as it works (builds/runs as usual), then it should be valid. The only exception to this I think would be if for whatever reason the author specifically doesn't want it to be built with such a compiler (I don't know of any reason that would be the case, but as a rule we always defer to authors).

So essentially, I think that so long as it works, we can change it to only require GCC 8 at minimum, since I presume it won't work with 7 at all.

**Comment by saukijan** [comment]
Thanks for the clarification @Ahajha. I opened a bug report for the cpr package. If no one opposes the idea I will drop the GCC requirement to 8
