### ISSUE TITLE
[package] qt/6.7.0: Version conflict in vulkan-headers dependency with vulkan=true

### ISSUE THREAD

**Issue by neobrain** [conan-io/conan-center-index#23684]
### Description

Qt pulls in multiple versions of vulkan-headers (`qt/6.7.0`->`vulkan-loader/1.3.268.0`->`vulkan-headers/1.3.268.0` and `qt/6.7.0`->`moltenvk/1.2.2`->`vulkan-headers/1.3.239.0`, leading to a conflict:

```
Version conflict: Conflict between vulkan-headers/1.3.239.0 and vulkan-headers/1.3.268.0 in the graph.
Conflict originates from moltenvk/1.2.2
```

### Package and Environment Details

* Package Name/Version: **qt/6.7.0**
* Operating System+version: **macOS Sonoma 14.4.1**
* Compiler+version: **clang 15**
* Conan version: **conan 2.2.3**
* Python version: **Python 3.12.3**

### Conan profile

[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos

### Steps to reproduce

conan install --requires qt/6.7.0 -o 'qt/*:with_vulkan'=True

### Logs

_

**Comment by jcar87** [comment]
Thanks @neobrain  - the issue here in the Qt recipe is that the dependencies cannot have versions independently, as they have very strict compatibility. I've fixed this in https://github.com/conan-io/conan-center-index/pull/24903 and added a note in the recipe so that versions aren't bumped without checking first.

**Comment by neobrain** [comment]
Thanks! I can confirm with the PR I no longer need any workarounds to resolve the conflicts :)
