### ISSUE TITLE
[package] capnproto/1.0.2: arch=x86_64 ignored when building on Apple Silicon macOS

### ISSUE THREAD

**Issue by li-dl** [conan-io/conan-center-index#23765]
### Description

Using an Apple Silicon Mac, trying to cross-compile capnproto to `arch=x86_64` but the resulting library is arm64.

### Package and Environment Details

* Package Name/Version: **capnproto/1.0.2**
* Operating System+version: **macOS 13.6.4**
* Compiler+version: **apple-clang 15.0.0** (Xcode 15.2)
* Conan version: **conan 1.61.0**

### Conan profile

```
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.version=15
compiler.libcxx=libc++
os=Macos
```

### Steps to reproduce

```
% cat conanfile.txt
[requires]
capnproto/1.0.2
[generators]
make

% mkdir build

% cd build

% conan install -pr:b ../profile -pr:h ../profile -b missing ..
...
libtool: install: ranlib /Users/username/.conan/data/capnproto/1.0.2/_/_/package/0033df8fad056d5819d0f2f7a4c73937aa31ed0b//lib/libcapnp.a
...

% cd /Users/username/.conan/data/capnproto/1.0.2/_/_/package/0033df8fad056d5819d0f2f7a4c73937aa31ed0b//lib

% lipo -info libcapnpc.a
Non-fat file: libcapnpc.a is architecture: arm64
```

### Logs

[ConsoleOutput.txt](https://github.com/conan-io/conan-center-index/files/15127610/ConsoleOutput.txt)

**Comment by SpaceIm** [comment]
Your build profile is incorrect, it must not be the same as host profile in case of cross compilation.

**Comment by li-dl** [comment]
> Your build profile is incorrect, it must not be the same as host profile in case of cross compilation, otherwise conan assumes a native build obviously.

Sorry, I probably shouldn't have used the words "cross compile". Technically, I guess it's not cross compiling, but my understanding was that we could use `arch=x86_64` in the build profile on an Apple Silicon Mac to force use of the x86_64 compiler via Rosetta 2. Is that not the case?

The reason we've been doing it that way is that we have a dependency on the hdf5 package, which can't be cross compiled yet. (Reported as #23803.)

**Comment by uilianries** [comment]
@li-dl Hello, in order to cross-compile a project, you should define different profiles. You can have a look in Conan documentation about this topic: https://docs.conan.io/2/examples/cross_build.html

>  we could use arch=x86_64 in the build profile on an Apple Silicon Mac to force use of the x86_64 compiler via Rosetta 2. Is that not the case?

You should be able to do that, but only in case the project in question supports cross-building, and the Conan recipe is prepared to work with cross-compilation.

The way you have explained, the ConanCenterIndex uses daily to generate Mac packages, there are M1 machines building x86_64 packages.

> The reason we've been doing it that way is that we have a dependency on the hdf5 package, which can't be cross compiled yet. (Reported as https://github.com/conan-io/conan-center-index/issues/23803.)

Thank you for pointing the origin of your question. Indeed that package can not be cross built yet, but it does not mean capnproto is not working. So, let's solve hdf5 first.

**Comment by uilianries** [comment]
I'm closing this issue because there is no restriction under capnproto, but it comes from hdf5.

Feel free to re-open in the future in case the error persist after fixing hdf5 package.

**Comment by uilianries** [comment]
Re-opening the issue because capnproto does not need HDF5 to be built: https://github.com/conan-io/conan-center-index/blob/master/recipes/capnproto/all/conanfile.py

Need to check if we can cross-build from arvm8 to x86_64. Let's build was in 2023, when machines were intel by default.

**Comment by uilianries** [comment]
It's possible to cross-compile CapnProto from armv8 to x86_64. It was done in the PR https://github.com/conan-io/conan-center-index/pull/22378 to generate the version 1.0.2 only few weeks ago.

Package ID for Apple Clang 13, Cppstd 17, All shared, x86_64

```
conan cache path capnproto/1.0.2#6c99e4ee392b0ba85eca415386d237bb:65e66c1936b1cff9ba8b5f7da71b580b519225c2                                                                                                                                                    
/Users/uilian/.conan2/p/capnpa51135ba3aa99/p

file /Users/uilian/.conan2/p/capnpa51135ba3aa99/p/lib/libcapnp.dylib                                                                                                                                                                                          
/Users/uilian/.conan2/p/capnpa51135ba3aa99/p/lib/libcapnp.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```

Since the beginning of the year, the CI only have M1 machines, and to provide x86_64, it cross-build.


Closing this issue again 😅 But feel free to re-open in case finding that's not possible to cross-build locally.
