### ISSUE TITLE
[package] nlohmann_json/3.11.3: Requiring nlohmann_json in a library does not transitively issue required generators.

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan-center-index#23970]
### Description

Let's describe a minimal example reproducing the issue.

Library `A` depends `nlohmann_json/3.11.3` and `spdlog/1.13.0`. (note: the issue is the same with other nlohmann_json versions).
If a downstream `B` depends on `A` (for example, the downstream could be `A`'s test_package), we need it to locate both `nlohmann_json` and `spdlog`: this gives the ability to issue `find_package()` statements for those requirements in `B` CMake scripts.

With `spdlog`, this works as expected. But with `nlohmann_json`, `find_package()` is failing with error:
> Could not find a package configuration file provided by "nlohmann_json".

Investigating further, we can see that `B`'s `generators` folder contain generators for `A`, for `spdlog` and its upstreams, but not for `nlohmann_json`, which explains why `find_package()` is failing.

### Package and Environment Details

* Package Name/Version: **nlohmann_json/3.11.3**
* Operating System+version: **macOS 12.6.5**
* Compiler+version: **Apple clang 14.0.0**
* Conan version: **conan 2.2.3**
* Python version: **Python 3.11.4**

### Conan profile

--

### Steps to reproduce

Please see the minimal example in the description.

### Logs

--

**Comment by SpaceIm** [comment]
I believe your issue is not related to conan-center-index. I don't think it's a bug, but a question you should ask to conan: https://github.com/conan-io/conan/issues.

It's likely related to the fact that you have written a conanfile of `B` where `nlohmann_json` is a private dependency of `B`, so indeed conan generators don't generate anything for `nlohmann_json` when you call in the context of a recipe depending on `B`, since `nlohmann_json` is header-only. But well it's related to conan client, not to `nlohmann_json` recipe.

**Comment by SpaceIm** [comment]
> (we do not make any explicit statement that it would be private)

As I said, in conan v2 dependencies are private by default

> and importantly, we declare it exactly the same as any other dependency (which are not header only, but from our perspective this is a detail of the upstream which should not change so radically how downstreams behave).
> (...)
> And from that trivial requirement declaration, spdlog issues generators transitively (as it did with Conan V1, and as we came to expect), but nlohmann_json does not.

The fact that conan generates CMake config file for private transitive dependencies if transitive library is static/shared and not when it's header-only is related to conan client. There is no issue in recipes themselves.

Now for your recipe `B`, if CMakeLists of `B` calls `find_package()` on `nlohmann_json` and `spdlog`, these 2 libraries should be direct requirements of `B` (otherwise you have no reason to call `find_package()` on these 2 libraries, they are internal details of `A`), you shouldn't rely on transitive dependencies coming from `A`.

**Comment by Adnn** [comment]
I missed your edit @SpaceIm , sorry.

Even though it feels "surprising" that implicit visibility now changes depending on the context, it is a Conan V2 decision.

--- 
Just a clarification, which does not change the fact that this is not a bug.

>Now for your recipe B, if CMakeLists of B calls find_package() on nlohmann_json and spdlog, these 2 libraries should be explicitly declared as direct requirements in recipe B (otherwise you have no reason to call find_package() on these 2 libraries, they are internal details of A), you shouldn't rely on transitive dependencies coming from A.

Not necessarily, see this statement from [CMake documentation](https://cmake.org/cmake/help/latest/guide/importing-exporting/index.html#creating-packages):

> All required dependencies of a package must also be found in the package configuration file.

This means that a well behaved CMake package config file will call `find_package()` on all libraries it depends upon, and this call will occur in the context of the leaf project (even though the package whose config actually issue the call can be arbitrarily high in the dependency tree).
Because of that, in any non-trivial project, the CMake configure step will need to find packages that the leaf project has no business knowing about.

**Comment by Adnn** [comment]
Not-a-bug, the libraries are not transitive by default in Conan v2.
