### ISSUE TITLE
[request] steamworks_sdk/1.60

### ISSUE THREAD

**Issue by PyroFlareX** [conan-io/conan-center-index#24672]
### Package Name/Version

steamworks_sdk/1.60

### Webpage

https://partner.steamgames.com/doc/gettingstarted

### Source code

https://partner.steamgames.com/?goto=%2Fdownloads%2Fsteamworks_sdk.zip

### Description of the library/tool

Steamworks is a set of tools and services that help game developers and publishers build their games and get the most out of distributing on Steam.

**Comment by valgur** [comment]
@PyroFlareX It's quite unlikely that the Steamworks SDK can be added to ConanCenter due to the non-OSS [license agreement](https://partner.steamgames.com/documentation/sdk_access_agreement) that the developer must accept before using it.

However, I gave it a shot on my fork, if it helps: https://github.com/valgur/conan-center-index/blob/dev/recipes/steamworks_sdk/all/conanfile.py
I have not tested it on Windows or macOS, but it should be a decent start, I think.

**Comment by AbrilRBS** [comment]
Hi @PyroFlareX thanks for the request. This is something I looked at back when too, and as @valgur correctly mentions, this is not something that could be added to CCI for their license agreement.

I'm the first that would love for it to be made available from CCI, but it's probable that the only way would be to rely on community created ones such as Valgur's - sorry for the inconvenience :)
