### ISSUE TITLE
[question] Support for Boost components, like Vcpkg has

### ISSUE THREAD

**Issue by wouterbeek** [conan-io/conan-center-index#24718]
### What is your question?

In Conan2, all of Boost must be pulled in, even though most users only need one or two components. If no precompiled version is available, this moreover means that all of Boost's source code is downloaded, and all of Boost's source code is built locally, even though only one components is used.

Boost has support for components, which can for example be expressed in CMake in the following way ("only use Boost Spirit"):

```
find_package(Boost REQUIRED COMPONENTS spirit)
```

Vcpkg supports this, since it delivers all of Boost, in addition to each component of Boost (e.g. "boost-spirit" for the above example).

Can Conan2 do this as well? If so, how does this work? If so, why is this not advertised in Conan Center, on the Boost page?

**Comment by uilianries** [comment]
@wouterbeek Hello! Thank you for your suggestion! Indeed your idea was discussed one or two times in the past, and we have similar issues here in CCI:

- https://github.com/conan-io/conan-center-index/issues/4298
- https://github.com/conan-io/conan-center-index/issues/11085

The idea was split Boost recipe in several modules, as you described, but in [conan-recipes-contrib](https://github.com/conan-io/conan-recipes-contrib), as it may require a different layout, because Boost components may depend each other. So, it's something that Conan team is inclined to have.

However, we still are missing the tools needed to execute this project, first we would need B2 Deps and B2 Toolchain feature available in Conan client. Otherwise, it would look a mess like we have now in the current Conan recipe for Boost, where we execute b2 step-by-step in the recipe. 

Both features are stopped/waiting in PRs in the Conan client repository. Boost offers CMake support, but the only official build process is via b2, this is documented in their repository.

**Comment by wouterbeek** [comment]
Thank you @uilianries for the detailed answer!

**Comment by uilianries** [comment]
@wouterbeek In case you want to follow the B2 Deps feature, the PR is this one: https://github.com/conan-io/conan/pull/13592
