### ISSUE TITLE
[package] libjxl/0.10.3: Problem in the include file generated from template by bazel

### ISSUE THREAD

**Issue by mmomtchev** [conan-io/conan-center-index#24798]
### Description

In `build/Release/lib/include/jxl/jxl_cms_export.h`:

```c
#  ifndef JXL_CMS_EXPORT
#    ifdef jxl_cms_EXPORTS
        /* We are building this library */
#      define JXL_CMS_EXPORT 
#    else
        /* We are using this library */
#      define JXL_CMS_EXPORT 
#    endif
#  endif
```

when it should be (when the library is compiled without `conan`:

```c
#  ifndef JXL_CMS_EXPORT
#    ifdef jxl_cms_EXPORTS
        /* We are building this library */
#      define JXL_CMS_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define JXL_CMS_EXPORT __attribute__((visibility("default")))
#    endif
#  endif
```

What is truly remarkable is that `jxl_export.h` is correctly generated, while `jxl_threads_export.h` has the same problem.

### Package and Environment Details

* Package Name/Version: **libjxl/0.10.3**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **GCC 11**
* Conan version: **conan 2.3.1**
* Python version: **Python 3.11.2**

### Conan profile

Host profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

Build profile:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

### Steps to reproduce

`conan install --requires libjxl/0.10.3`

### Logs

N/A

**Comment by perseoGI** [comment]
Hi @mmomtchev 

Have in mind that `libjxl` in upstream has two ways of building it, one with CMake and another with Bazel.
CCI recipe is using the CMake build system so I don't really understand the title of this PR.

I've successfully compiled this library using conan and as you notice, `jxl_cms_export.h` and `jxl_threads_export.h` do not provide `__attribute__((visibility("default")))`

I've managed to compile the upstream code and it do provides those missing attributes, same for installing through apt.

Here is the upstream code which generates this files:
- jxl_cms_export: https://github.com/libjxl/libjxl/blob/56b6e93075e8eacd21019d0e161e166a631417d5/lib/jxl_cms.cmake#L11-L25
- jxl_export: https://github.com/libjxl/libjxl/blob/56b6e93075e8eacd21019d0e161e166a631417d5/lib/jxl.cmake#L65-L74

I'm pinging @valgur to see if he can take a look to this issue, because this seems to be a really strange behavior.

**Comment by valgur** [comment]
I looked into it and can reproduce it, but the attributes are only missing if the library type is STATIC. SHARED and OBJECT work as expected.

`generate_export_header()` apparently does not output these attributes when building as STATIC: https://github.com/Kitware/CMake/blob/master/Modules/GenerateExportHeader.cmake#L304-L313

I suspect the difference is simply caused by libjxl building as SHARED by default (https://github.com/libjxl/libjxl/blob/v0.10.3/CMakeLists.txt#L93) while the recipe defaults to STATIC.

**Comment by perseoGI** [comment]
Good catch @valgur thank you very much!

I've tested myself and, compiling with `-o "&:shared=True`, @mmomtchev you should get a code like what you were expecting:

```cpp
#  ifndef JXL_CMS_EXPORT
#    ifdef jxl_cms_EXPORTS
        /* We are building this library */
#      define JXL_CMS_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define JXL_CMS_EXPORT __attribute__((visibility("default")))
#    endif
#  endif
```

Do you have any further questions?

**Comment by mmomtchev** [comment]
Yes, I confirm, this is an upstream bug
