### ISSUE TITLE
VTK 9.x.x in OpenCV 4.9

### ISSUE THREAD

**Issue by mega-clueless** [conan-io/conan-center-index#25026]
Hi,
I am new to C++, cmake, conan and conancenter, I apologize in advance if I say something wrong. 
I am using OpenCV 4.9 from conancenter and want to use VTK. I have a VTK conan package in my local cache (inspiration from https://github.com/darcamo/conan-vtk), I have commented out the exception for using the viz module. VTK and OpenCV with viz enable builds nicely and throws no error. I even see VTK in the OpenCV configuration.
![image](https://github.com/user-attachments/assets/71900c30-4348-470d-84bc-67145a1c3dbc)

But when I open my application then I get the following CMAKE error:
CMake Error at build/generators/OpenCV-Target-release.cmake:232 (set_property):
The link interface of target "opencv_viz_DEPS_TARGET" contains:
vtk::vtk
but the target was not found.

Does anyone know how to solve this?

**Comment by valgur** [comment]
My guess is that this is due to no real `cpp_info` being actually defined by the VTK recipe you are using and the recipe relying on the installed CMake config files instead. As a result, the recipe can only be consumed as a direct dependency and Conan is not able to provide it correctly as a transitive one.

You can try this complete VTK recipe instead:
- #24808

**Comment by mega-clueless** [comment]
Hi @valgur,
Thank you for your speedy reply.
I have been trying to build with the recipe  but got errors, some of which I managed to get rid of, but then there is:
ERROR: vtk/9.3.1: Required package 'double-conversion' not in component 'requires'

Do you have any suggestions on how to resolve this error?
