### ISSUE TITLE
[request] zpp_bits/4.4.24

### ISSUE THREAD

**Issue by YanzhaoW** [conan-io/conan-center-index#25581]
### Package Name/Version

zpp_bits/4.4.24

### Changelog

https://github.com/eyalz800/zpp_bits/releases/tag/v4.4.24

### Context about the new update

The above-mentioned version is newly released by the upstream project and not yet available as a recipe.
Please add this version.

**Comment by toge** [comment]
@YanzhaoW 
Thank you for your request!

The reason zpp-bit has not been updated since 4.4.20 is that the code modification are the internal variable names change only.

Please check the following diffs.
https://github.com/eyalz800/zpp_bits/compare/v4.4.20...v4.4.24

I did not intend to update it voluntarily, but I will create a PR if it is necessary for you to have the latest version.

**Comment by YanzhaoW** [comment]
Hi, 

Thanks for your response. I got a compiler error from the version v4.4.20 due to the member function `is_value()` not found. This error was fixed in this [commit](https://github.com/eyalz800/zpp_bits/commit/2fa24112425ace55ae27a75f717ae0fd054097a0).

Yes, it would be really nice if you could update it to the latest version.

**Comment by toge** [comment]
@YanzhaoW 
Thank you for your detail explain!
Now I see.

I created the PR for it.
Please wait a moment until merge.
