### ISSUE TITLE
Openssl reference to zlib

### ISSUE THREAD

**Issue by klausholstjacobsen** [conan-io/conan-center-index#25635]
Hello fellow conaneers!

I see in the following in the openssl recipe:

https://github.com/conan-io/conan-center-index/blob/0c86693f18b14e52d7119b3e225706a002f27a9e/recipes/openssl/3.x.x/conanfile.py#L654

It references "zlib::zlib", which in cmake becomes a link target with the same name, but zlib does not expose such a target, instead it exposes "ZLIB::ZLIB".

https://github.com/conan-io/conan-center-index/blob/0c86693f18b14e52d7119b3e225706a002f27a9e/recipes/zlib/all/conanfile.py#L101

This is also reflected in the generated cmake package config file ZLIBTargets.cmake:

![image](https://github.com/user-attachments/assets/e3db6909-0b3a-4688-8319-b9c229450ba2)

Is this an error or is there some underlying assumption that I am not aware of.

In my case I am iterating dependencies in a custom generator.
When I get to the dependencies of openssl I cannot lookup "zlib::zlib" and cannot resolve the relation between the cmake link target "zlib::zlib" and the zlib package itself.

Should I assume that I can always resolve a package with [package_name]::[package_name]?

My question boils down to. When openssl depends on "zlib::zlib" how can I then resolve that this is actually the zlib package we're talking about?

Regards
Klaus

**Comment by SpaceIm** [comment]
It's more a question for conan repo, rather than conan-center-index.

CMake target name in CMakeDeps is equal to conan "requires" name by default, but it can be overridden by `cmake_target_name` (which the case in zlib recipe, in order to follow https://cmake.org/cmake/help/latest/module/FindZLIB.html).
Don't forget that conan "requires" names are an just an internal conan abstraction (it's just recipeName::recipeName), there are many possible conan generators (CMakeDeps, PkgConfigDeps etc) and possible name mapping for these generators.

When you see `self.cpp_info.components["crypto"].requires.append("zlib::zlib") ` in `package_info()` of a recipe which depends on zlib recipe, it is translated to appropriate CMake target name by CMakeDeps (based on `cmake_target_name` property of zlib recipe).

**Comment by klausholstjacobsen** [comment]
Thanks, I will cross post to conan repo!
