### ISSUE TITLE
[question] Conan 2 conancenter is missing Linux clang and debug binaries

### ISSUE THREAD

**Issue by battlmonstr** [conan-io/conan-center-index#25691]
### What is your question?

Hello,

Could you confirm that:
Conan 1.x conancenter used to have clang 13 binaries for Linux and debug binaries for all platforms.
Conan 2.x conancenter doesn't have clang binaries for Linux, and no debug binaries at all.

If true, could you explain what's the rationale for these decisions and if there are any plans to add support for this in the future? If there are plans, what's an ETA?

Is there a documentation page that contains lists configurations that conancenter has binaries for?
I can find this info by running a command per package, grouping similar configurations, and filtering, but I was wondering if it is already stated somewhere? It would be useful to have it documented.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
Ticket moved to the conan-center-index repo.

**Comment by jcar87** [comment]
Hi @battlmonstr - thank you for your question.

There are multiple aspects behind this. Simultaneously supporting Conan 1.x and Conan 2.x for all recipes (so far) has meant quite a considerable resource utilisation in our CI infrastructure.

A single pull request may result in generating packages for all versions in the recipe (that the PR targets), for all platforms/compilers that we support, in multiple configurations (e.g. shared and static). For example right now a PR for OpenSSL would generate ~100 packages in Conan 2, plus a similar number in Conan 1.  

So we had to make certain compromises to ensure that the service runs as smoothly as possible. 

On the other hand, when deciding which configurations to discontinue support for, we made a few observations:
* binaries are far more likely to be requested for gcc versions that align with Ubuntu LTS, and less so for other gcc versions
* binaries are far more likely to be requested for Release - especially on Linux these are also binary compatible when the consumer project is in Debug
* clang binaries were requested used a lot less in general
* related to the point above, the more frequent releases of clang means that the versions in use are more "scattered" than gcc ones, making it even more unlikely for the binaries to se useful/downloaded by enough users to make the effort justifiable. Roughly, there are about ~3 major releases in play within a 12-month period. So our clang builds served more a purpose of validating "does this build on recent enough clang", rather than the binaries being useful for a significant number of users
* in terms of "does this build on recent enough clang" - to a limited extent, certain compiler issues with the apple-clang compiler on macOS have a history of correlating with the same issues appearing in linux/clang 

Conan 1.x still builds clang13 Release binaries, but not for very long (see [announcement](https://github.com/conan-io/conan-center-index/discussions/25461))

Once we deprecate Conan 1.x binaries are per the above announcement, and we are roll out our new CI infrastructure in coming weeks, we have plans to add more platform support for Conan 1.x binaries - realistically, I wouldn't expect these to happen until early Q1 2025.

The current supported platforms in Conan 2.x are:
- gcc11, apple-clang 13 (intel and arm), visual studio 2019 and visual studio 2022  - in all cases release only

Once our new infrastructure is in place, I would say we would prioritise longstanding issues: 
- add at least 1 clang build on Linux
- use a newer version of gcc on Linux
- use a newer version of apple-clang on macOS
- we will consider debug binaries, but I'd imagine Windows has a higher priority (as release binaries are incompatible when the consumers are in debug)
