### ISSUE TITLE
[question] Where is `drogon_ctl` executable?

### ISSUE THREAD

**Issue by lbagneres-enigma** [conan-io/conan-center-index#25750]
### What is your question?

Hi,

Here is my `conanfile.txt`
```
[requires]
drogon/1.9.7

[generators]
CMakeDeps
CMakeToolchain

[options]
drogon/*:with_postgres=True
drogon/*:with_ctl=True
```

Here are the commands I use:
```
conan profile detect --force
conan install . --output-folder=build_conan -s build_type=Release --build="*"
```

Where is the `drogon_ctl` executable?
I cannot find it in `./build_conan` directory. I did find it in the `~/.conan2/p/b/drogob7709aa1b7acc/p/bin` directory, but that is not predictable.

Thank you.

**Comment by uilianries** [comment]
@lbagneres-enigma Hello! You are looking from `deploy` feature, not only installing the package in your Conan cache. In order to do that, you have to pass extra parameters to your installation command:

    conan install . --output-folder=build_conan -s build_type=Release -d direct_deploy --deployer-folder deploy

The `build_conan` folder will contain the generators, like `conan_toolchain.cmake` and other cmake files. The folder `deploy` will contain what you are looking for:

```
ls deploy/direct_deploy/drogon/bin/
dg_ctl  drogon_ctl
```

Please, read https://docs.conan.io/2/reference/extensions/deployers.html#built-in-deployers to get more information about supported Deployers in Conan client. Plus, you can write custom deployer to customize the output. 

Regards!

**Comment by lbagneres-enigma** [comment]
Thank you, it works :)
With `--deployer=direct_deploy` option, `build_conan/direct_deploy/drogon/bin/drogon_ctl` is installed.
