### ISSUE TITLE
[package] xxhash/0.8.2: missing options

### ISSUE THREAD

**Issue by vasama** [conan-io/conan-center-index#25778]
### Description

The recipe is missing options for `XXH_STATIC_LINKING_ONLY` and `XXH_IMPLEMENTATION` (header only).

### Package and Environment Details

* Package Name/Version: **xxhash/0.8.2**

### Conan profile

N/A

### Steps to reproduce

N/A

### Logs

N/A

**Comment by SpaceIm** [comment]
Could you clarify what you want exactly? Would you want xxhash recipe to expose a header_only option so that it would just package header of xxhash without any compilation? I don't see any reason to do that in a package manager.

**Comment by vasama** [comment]
> I don't see any reason to do that in a package manager

Yeah, usually I would agree. In this case there's a clear performance benefit to enabling inlining of those functions, however.

`XXH_STATIC_LINKING_ONLY` on the other hand is required for static allocation of hash states.

**Comment by SpaceIm** [comment]
XXH_STATIC_LINKING_ONLY is defined by default through compilation of xxhah.c https://github.com/Cyan4973/xxHash/blob/v0.8.2/xxhash.c#L40

Well feel free to open a PR adding `header_only` option. No need to add other options since it doesn't make sense when we are building xxhash (`XXH_STATIC_LINKING_ONLY` always defined by design), and if it's header_only, users are on their own and free to define `XXH_STATIC_LINKING_ONLY` or not themselves (it's how all "C header only" libraries work in conancenter recipes, users are responsible of defining IMPLEMENTATION macro stuff themselves, and eventually the STATIC macro stuff when it exists).
