### ISSUE TITLE
[service] zero packages generated - should be an error

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#258]
example: https://github.com/conan-io/conan-center-index/pull/157#issuecomment-548264402
it should be suspicious if zero packages were generated for PR
(e.g. it always throws `ConanInvalidConfiguration`?)
such builds should be marked as failed by CI/conan bot.

**Comment by Hopobcn** [comment]
Another case of https://github.com/conan-io/conan-center-index/pull/431 `Generated 0 packages`. 
It's interesting because both cases (#157 and #431), are header-only libs with requirements on C++17.

Regarding `cpp-taskflow` PR. I started getting the `Generated 0 packages` message after I switched from manually checking for C++17 to using the new `tools.check_min_cppstd(self, "17")`. https://github.com/conan-io/conan-center-index/pull/431/commits/df7553f5e6c4a0e2c809329fb34271c9e5db1e75

The logs are exactly the same as #157 :
```
{
  "errors" : [ {
    "status" : 404,
    "message" : "{\"error\":\"Item misc:logs/pr/431/8/cpp-taskflow/2.2.0 does not exist\"}"
  } ]
}
```

**Comment by uilianries** [comment]
Hi @Hopobcn Thanks for reporting!

**Comment by danimtb** [comment]
This was fixed some time ago https://github.com/conan-io/conan-center-index/blob/master/docs/changelog.md#17-august-2020---1120-cest
