### ISSUE TITLE
[package] libx264/cci.20240224: undefined attribute self._settings_build

### ISSUE THREAD

**Issue by valenotary** [conan-io/conan-center-index#26098]
### Description

FFMPEG release build is failing because Libx264 dependency cant be built due to this undefined attribute. I can't find any documentation on it either, I only know of `self.settings_*` as opposed to `self._settings_*`... Is this just a documentation miss, or has this package not been updated properly?

### Package and Environment Details

* Package Name/Version: **libx264/cci.20240224**
* Operating System+version: **Mac OS**
* Compiler+version: **Apple Clang**
* Conan version: **conan 2.X**
* Python version: **Python 3.11.X**

### Conan profile

[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=14
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

regular conan install on my custom package, which directly requires ffmpeg (libx264 is required by ffmpeg)

### Logs

<details><summary>Click to expand log</summary>

```
AttributeError: 'LibX264Conan' object has no attribute '_settings_build'. Did you mean: 'settings_build'?
```

</details>

**Comment by uilianries** [comment]
@valenotary Hello and thank you for reporting! Indeed it's a bug in the recipe and I see the PR #26100 should be fixing. We will be reviewing the PR during this day.

The `self.settings_build` was introduced in the middle of Conan 1.x (see https://docs.conan.io/1/systems_cross_building/cross_building.html#conan-v1-24-and-newer) and when cross-building using two profiles (build and host) the `self.settings_build` should be available. As in Conan 1.x it was not guaranteed due the use of single profile when cross-building, we had an idiom for recipes like this:

```python
def self._settings_build(self):
    return getattr(self, "settings_build", self.settings)
```

This idiom is deprecated in Conan 2.x, because in this new Conan version, we always had 2 profiles available. So we can remove method, but as you can see, this leftover caused your bug.

You still can find a good number of recipes using this method in CCI, but it should not break in Conan 2.x, so we are equally safe.
