### ISSUE TITLE
[boost] boost/1.74: recipe_folder not defined

### ISSUE THREAD

**Issue by gummif** [conan-io/conan-center-index#3897]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.74**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.25.0**
  * Python version: **Python 3.5.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)

run
```
conan install --update .
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: boost/1.74.0: Error in config_options() method, line 187
        for opt_name in self._configure_options:
while calling '_configure_options', line 198
        return self._dependencies["configure_options"]
while calling '_dependencies', line 138
        dependencies_filepath = os.path.join(self.recipe_folder, "dependencies", self._dependency_filename)
        AttributeError: 'BoostConan' object has no attribute 'recipe_folder'

```

</details>

**Comment by gummif** [comment]
Looks like updating conan fixes this issue. A better error message would help.

**Comment by Croydon** [comment]
The Boost recipes is marked as compatible for `>= 1.28.0`

https://github.com/conan-io/conan-center-index/blob/2cad9a7843ec8eb935b5023dd19b4a695a45fb08/recipes/boost/all/conanfile.py#L18

However, the attribute itself was only introduced in Conan 1.28.0, since you used 1.25.0 you did not get a good error message.

This shouldn't happen for future incompatibilities as long as the attribute gets updated correctly and at least Conan 1.28.0 is used.

I would suggest to close this issue.

**Comment by gummif** [comment]
OK will close this now.
