### ISSUE TITLE
[question] Settings on headers only libraries

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#3929]
Hello everyone,

I've noticed that some recipes have the standard settings listed (os, arch, compiler, build_type) even though we are dealing with a headers only library.
What is the reason for that? Are there any drawbacks with removing them?

As an example, the pybind11 recipe
https://github.com/conan-io/conan-center-index/blob/master/recipes/pybind11/all/conanfile.py#L13

Or the eigen one:
https://github.com/conan-io/conan-center-index/blob/master/recipes/eigen/all/conanfile.py#L13

Thanks!

**Comment by SpaceIm** [comment]
It depends.
Some header only recipes have settings, just because packing is done with CMake, to prevent (harmless?) warnings.
But some recipes also need to know:
- compiler version to check if some C++ standard is supported
- os to add system libs in `package_info()`

The assumption that header only libraries = settings is wrong.
But header only **packages** usually don't depend on settings, so it is removed from package_id.
