### ISSUE TITLE
[question] eol=lf only for a few files, breaks libcurl if exported from Linux and Windows

### ISSUE THREAD

**Issue by sturmf** [conan-io/conan-center-index#3948]
I saw that recently a .gitattributes file was added which sets the line ending for a couple of file endings. This helped a lot with outdated recipes problems. But since the hash calculation of a recipe also takes the exported file into consideration, it breaks with e.g. libcurl.

The libcurl recipe has the file [lib_Makefile_add.am](https://github.com/conan-io/conan-center-index/blob/master/recipes/libcurl/all/lib_Makefile_add.am) checked into conan-center-index but this line ending is not in .gitattributes.

Therefore my question, wouldn't it make sense to either add this file ending to the .gitattributes file too or even more broadly make all text files have lf as line ending? Or am i doing something wrong and therefore I am the only person with this specific problem?

**Comment by SSE4** [comment]
this is something to carefully consider on a case by case basis. 
for instance, there are text files that always must have Linux line-endings (LF), such as `Makefile`
on the other hand, there are text files that always must have Windows line-endings (CRLF), such as `.rc` (resources - otherwise Microsoft Resource Compiler fails)
for `.am` files, we know that they are GNU automake files, and we can add them to .gitattributes.
