### ISSUE TITLE
[package] opencv/4.5.1: does not have dnn support

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#4016]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **opencv/4.5.1**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9.3.0**
  * Conan version: **conan 1.32.1**
  * Python version: **Python 3.8.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9.3
os=Linux
os_build=Linux
[options]
*:fPIC=True
opencv*:contrib=True
[build_requires]
[env]

```

### Steps to reproduce (Include if Applicable)
conan install opencv/4.5.1@ -o opencv*:contrib=True --build missing

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
not relevant - module is missing; build is ok
```

</details>

**Comment by AndreyMlashkin** [comment]
Previous version opencv/4.3.0@conan/stable contained the DNN module with default options

**Comment by uilianries** [comment]
OpenCV/4.3.0 is deprecated and wasn't part of Conan Center Index. I'll check it. Thanks for reporting

**Comment by uilianries** [comment]
DNN is only used with protobuf, but protobuf is not included as requirement. It deserves an update.

**Comment by andioz** [comment]
> DNN is only used with protobuf, but protobuf is not included as requirement. It deserves an update.

Yes I recognized too, I guessed this will be requested soon :) I think it is a little bit more complicated, because of the indirect `protobuf` dependency. The officially used version is not in CCI, if I remember right (too old). And there is a optional `recompile` option for protoc files, not sure if it would be useful for a standard recipe installation...

`protobuf` is enabled by default in OpenCV's CMakeLists.txt, therefore it should be the samein the recipe?

**Comment by AndreyMlashkin** [comment]
We can add "with_protobuf" flag with default value True in order to have the same behavior as OpenCV defaults

**Comment by andioz** [comment]
I played with this for a few days now. Not so easy, because:
* OpenCV typically uses it's own copy of `protobuf`, which is an older version. I'm sure we don't want to use this. 
* If we want to use an external (and newer)  `protobuf` library, we need to recompile the `proto` files
* Therefore, we need a `protoc` compiler, for native build this if fine, but not for cross building. Currently we have no protobuf-compiler recipe, which can be used as build requirement.
* `protobuf` itself has some trouble for cross building, at least for Android, where a library `log` should be linked.
* Maybe more yet unknown problems...

I have a branch with experimental code for this. It compiles (but no DNN functions tested here, only building!) for Linux build machine and Linux and Android hosts right now. I will continue testing for Macos build machine and Macos, Android, iOS host machines too, because this is my current works setup. Windows I have no chance to test. 

Here is my branch: https://github.com/andioz/conan-center-index/tree/opencv4x/dnn

@uilianries @ericLemanissier @madebr and other experts in Conan, OpenCV and Protobuf: I need your help! Currently my branch is not ready for a PR, I would say. I need your input for cleaning up and making things right. I hacked a lot to make it work, but I'm sure there is a better way to make it work. Please check out my branch and let us discuss how to make it clean. I have touched 3 recipes:
* `opencv` of course - adding dnn, but need new requirement `protobuf` AND in case of cross compiling a build requirement `protobuf-compiler`, which doesn't exist yet
* `protobuf` - disabling compiler build because of missing log library linkage
* `protobuf-compiler` - a POC for a new recipe which installs the prebuild protoc packages for all versions supported by the `protobuf` recipe.

I'm currently using the "old" single profile strategy. If changes are required to make everything work with the "new" dual profile  strategy, I would prefer to make it work with both scenarios. 

Hope to CU there!

**Comment by Croydon** [comment]
There is no protobuf-compiler package and never will be because protoc is part of the protobuf package. IIRC you can also add the same requirement as a regular dependency and as a build_requirement at the same time (disclaimer: I have never done that)

To make it easier to provide feedback I would suggest that you open a pull request as a draft

**Comment by andioz** [comment]
> IIRC you can also add the same requirement as a regular dependency and as a build_requirement at the same time.

I'm sure I tried this first, but if I remember right the build requirement is not used in this case.
