### ISSUE TITLE
[service] Install ATL in Visual Studio 2015/2017 containers

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#4195]
ATL doesn't seem to be installed in Visual Studio 2015 and 2017 containers.
gdal >= 3.2.0 can't build without ATL: https://github.com/conan-io/conan-center-index/pull/3436#issuecomment-726135955

**Comment by jgsogo** [comment]
Having a look to this link: https://devblogs.microsoft.com/cppblog/finding-the-visual-c-compiler-tools-in-visual-studio-2017/ I see there are different ATL components:

 * Visual C++ ATL support - Microsoft.VisualStudio.Component.VC.ATL
 * MFC and ATL support (x86 and x64) - Microsoft.VisualStudio.Component.VC.ATLMFC

Are both needed?

**Comment by SSE4** [comment]
`ATL` is an Active Template Library, it's collection of wrappers for Microsoft COM technology (e.g. smart pointers to work on COM Objects)
`MFC` is a Microsoft Foundation Classes, it's GUI library containing wrappers for Windows Controls (e.g. buttons, check boxes)
`MFC` depends on `ATL`, that's why component is named `ATLMFC`
many applications use `ATL` or `MFC`, so we need to have both installed.

**Comment by SpaceIm** [comment]
@jgsogo, I'll submit a PR for `gdal`, it could be a good opportunity to enable Visual Studio 2015 & 2017 for gdal 3.2.1, is ATL available now for these agents?

**Comment by jgsogo** [comment]
According to our checks, ATL is now installed. We can keep this issue open until someone confirms.

**Comment by SpaceIm** [comment]
@jgsogo https://github.com/conan-io/conan-center-index/pull/9584 will confirm.

**Comment by jgsogo** [comment]
And it does 😊 

Thanks a lot, @SpaceIm
