### ISSUE TITLE
[service] Windows x86_64, Release, Visual Studio 16, MT is misbehaving

### ISSUE THREAD

**Issue by mathbunnyru** [conan-io/conan-center-index#4214]
I do think that this setup doesn't work properly.

These are the PRs where I see such a behaviour:
https://github.com/conan-io/conan-center-index/pull/4205
https://github.com/conan-io/conan-center-index/pull/3778

The symptoms are:
full log (including error), till the end
no actual error message

But the build is failing.

I checked the same configuration on my machine, and it works.
![Screenshot 2021-01-11 at 12 44 19](https://user-images.githubusercontent.com/12270691/104165992-252cd280-540b-11eb-8915-283ceee99430.png)

**Comment by ericLemanissier** [comment]
I had some other similar failures last week, which disappeared after re triggering the build

**Comment by mathbunnyru** [comment]
> I had some other similar failures last week, which disappeared after re triggering the build

Thanks, I will try restarting. Hope it will work.

**Comment by mathbunnyru** [comment]
Unfortunately, it's random Windows setups.

https://github.com/conan-io/conan-center-index/pull/4205#issuecomment-757909289

**Comment by dmn-star** [comment]
I think this happens because bin\util writes to std::cerr

https://c3i.jfrog.io/c3i/misc/logs/pr/4205/8/poco/1.10.1/745df211abc62d37eee894caf57dc01010e4f8d4/create_**stderr.**txt

>Command line:
bin\util 
Arguments to main():
Application properties:
application.argc = 1
application.argv[0] = bin\util
application.baseName = util
application.cacheDir = C:\J\w\cci_PR-4205@2\8\5bfd9578-f853-4666-ba20-9cec5c3db124\util\
application.configDir = C:\Users\conan\AppData\Roaming\util\
application.dataDir = C:\Users\conan\AppData\Local\util\
application.dir = C:\J\w\cci_PR-4205@2\8\556552b7-27d2-464b-92df-22a1e0c5417d\recipes\poco\all\test_package\build\afa536774ba7d62785bd32583a0e79ad2d05147e\bin\
application.name = util.exe
application.path = C:\J\w\cci_PR-4205@2\8\556552b7-27d2-464b-92df-22a1e0c5417d\recipes\poco\all\test_package\build\afa536774ba7d62785bd32583a0e79ad2d05147e\bin\util.exe
application.tempDir = C:\J\w\cci_PR-4205@2\8\5bfd9578-f853-4666-ba20-9cec5c3db124\util\
system.osName = Windows NT
system.osVersion = 6.2 (Build 9200)
system.osArchitecture = AMD64
system.nodeName = C3I-PROD-WIN1
system.nodeId = 42010aa30beb
system.currentDir = C:\J\w\cci_PR-4205@2\8\556552b7-27d2-464b-92df-22a1e0c5417d\recipes\poco\all\test_package\build\afa536774ba7d62785bd32583a0e79ad2d05147e\
system.homeDir = C:\Users\conan\
system.configHomeDir = C:\Users\conan\AppData\Roaming\
system.cacheHomeDir = C:\J\w\cci_PR-4205@2\8\5bfd9578-f853-4666-ba20-9cec5c3db124\
system.dataHomeDir = C:\Users\conan\AppData\Local\
system.tempHomeDir = C:\J\w\cci_PR-4205@2\8\5bfd9578-f853-4666-ba20-9cec5c3db124\
system.tempDir = C:\J\w\cci_PR-4205@2\8\5bfd9578-f853-4666-ba20-9cec5c3db124\
system.configDir = C:\ProgramData\
system.dateTime = 2021-01-11T11:46:07Z
system.pid = 10436

**Comment by mathbunnyru** [comment]
@dmn-star I don't think that's the case.
User should be able to write to cerr, it's not a bug to write there, cmake does in so many cases and recipes as well (there are many unused variables).

But, if I'm wrong and there is a documentation, which tells not to write to cerr, please, give me a link.

**Comment by dmn-star** [comment]
just my guess. I have often seen something like this

` stage('Monitoring the logs') {
    steps {
        script {
            while (BUILD_COMPLETE != true) {
                sh '! grep "^ERROR:" output.log'
                sleep 1
            }
        }
    }
}`
 in Jenkins pipelines.

You can simply comment out execution of the test temporarily and see if the next build is successful.
https://github.com/conan-io/conan-center-index/blob/master/recipes/poco/all/test_package/conanfile.py

**Comment by danimtb** [comment]
The situation around the windows machines of the service has greatly improved since this issue. Now the environment is much more controlled and we check the status of the machines regularly. Thank you!
