### ISSUE TITLE
[package] libcurl/all: doesn't seems to support --with-secure-transport on apple systems

### ISSUE THREAD

**Issue by pagikiw552** [conan-io/conan-center-index#441]
While going through `conan-center`'s [libcurl recipe](https://github.com/conan-io/conan-center-index/blob/master/recipes/libcurl/all/conanfile.py), I can't find any option to enable secure-transport which is available for apple systems. The support for this backend can be found - https://curl.haxx.se/docs/install.html under "Select TLS backend" heading.

While adding this param would be easy, simply by making it as a [option here](https://github.com/conan-io/conan-center-index/blob/master/recipes/libcurl/all/conanfile.py#L20) and appending to [params here](https://github.com/conan-io/conan-center-index/blob/master/recipes/libcurl/all/conanfile.py#L157) but I don't know how it will react with `darwin-ssl` and what should be the default option.

**Comment by Croydon** [comment]
Isn't there the option `darwin_ssl` for macOS?

**Comment by pagikiw552** [comment]
@Croydon darwin_ssl and secure_transport are two different backends, user might want to use one over another if there's a bug/feature that's present in one but not the other. Hence my request to add secure_transport as an option too.

**Comment by SpaceIm** [comment]
Actually, `with-darwinssl` option has been renamed `--with-secure-transport` since 7.64.1: https://github.com/curl/curl/commit/76a9c3c4be10b3d4d379d5b23ca76806bbae536a#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810
So it's the same feature, but `libcurl` recipe should be updated to take this modification into account.
