### ISSUE TITLE
[package] mongo-cxx-driver/3.6.2: this version appears twice

### ISSUE THREAD

**Issue by mathbunnyru** [conan-io/conan-center-index#4415]
@qchateau created a PR, which adds version 3.6.2 to the list of versions.

His commit was originally created 27 days ago (2 Jan 2021):
https://github.com/conan-io/conan-center-index/pull/4403/commits/32c42a596149bc72855e5175ec1d13f1afbe3776

The PR was created 29 Jan:
https://github.com/conan-io/conan-center-index/pull/4403

But I have already added version 3.6.2 before PR was accepted on 18 Jan:
https://github.com/conan-io/conan-center-index/pull/4057/files

There was no merge error, because I added the information to the end, and hist bot added it to the beginning.

**Comment by mathbunnyru** [comment]
@qchateau I think it's your bot is misbehaving, because it allowed you to create the PR for the recipe updated a while ago.

**Comment by mathbunnyru** [comment]
Right now version 3.6.2 appears twice:
https://github.com/conan-io/conan-center-index/blob/master/recipes/mongo-cxx-driver/config.yml

**Comment by qchateau** [comment]
Hey, I tried to find out what happened. Thankfully CCB keeps [the history of all its statuses](https://github.com/qchateau/conan-center-bot/commits/status/prod), but it seems that between the 18th of January and the 29th of January, the bot was correctly reporting the latest version to be "3.6.2", and did not link anymore to the branch it built on the 2nd of January.

When I opened #4403, I did it by clicking the link here https://github.com/qchateau/conan-center-bot/issues/53, and not from the CCB updatable page. My guess would be that this link was not available on CCB's updatable page anymore at this time.

**Comment by mathbunnyru** [comment]
My suggestion - maybe it would be helpful to delete update branches to make sure no one else makes a mistake like that.

**Comment by qchateau** [comment]
It's a technical solution which also brings its fair share of corner cases. And to be completely honest, I don't have much free time to allocate to CCB at the moment.
On the other hand I think there is no reason for this to happen again as it is the combination of singular events:
- There was no merge conflict
- The bot had removed the merge "quick link" but we kept it in the comments of an issue
- I opened the merge request without even taking a look at its content of usefulness because I was investigation a bug

**Comment by mathbunnyru** [comment]
Thanks, that's a good explanation. I will create a PR to remove the version duplication, which will close this issue.
