### ISSUE TITLE
[package] swig/4.0.2: same package_id for shared upstream dependencies

### ISSUE THREAD

**Issue by klimkin** [conan-io/conan-center-index#4941]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **swig/4.0.2**
  * Operating System+version: **Debian GNU/Linux 10 (buster)**
  * Compiler+version: **GCC 9.3**
  * Conan version: **conan 1.34.1**
  * Python version: **Python 3.9.2**

### Conan configuration

The package id mode:
~~~
default_package_id_mode = full_version_mode
~~~

### Steps to reproduce (Include if Applicable)

See commands below:
* first commands builds ok
* second command matches swig package id from the previous step and fails even if using `tools.run_environment`

`swig` package doesn't have `shared` option, so package id is not affected by the CLI option. I guess the package_id should have something similar to `self.info.shared_library_package_id()`.

~~~
$ conan create . swig/4.0.2@ -o '*:shared=True' --build=missing --build=swig

$ conan create . swig/4.0.2@ -o '*:shared=False' --build=missing
...
.conan/data/swig/4.0.2/_/_/package/8d9623162576838bf5e4e0b3fae3a5a1a6010552/bin/swig: error while loading shared libraries: libpcre.so: cannot open shared object file: No such file or directory
ninja: build stopped: subcommand failed.
ERROR: swig/4.0.2 (test package): Error in build() method, line 26
        self._cmake.build()
~~~

**Comment by perseoGI** [comment]
Hi @klimkin,
I was reviewing old issues and I have come across this one.

I'm closing this issue as this `swig` has suffer plenty of modifications since this issue was reported.
One of them solved this `shared` dependencies problem https://github.com/conan-io/conan-center-index/pull/19058/files#diff-5e54e3ca7550c41bb7c6ce862da78665379e1ad54b72f2212a31c3e1511b44c3R32

Happy coding 🐸
