### ISSUE TITLE
[package] sentry-native should use breakpad as a backend on Linux.

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#5067]
I'm posting this so we can keep track of this issue.

The `sentry-native` sdk can be built on Linux using its own backend, called `inproc` but its capabilities are limited. The recommended backend on Linux is `Breakpad` which is not yet available in conan-index.

We also need a recipe for `Crashpad` which is the default backend for Windows and MacOS (I have no idea about inproc's performance on those platforms)
https://github.com/getsentry/sentry-native/blob/master/CMakeLists.txt#L119

Related: https://github.com/conan-io/conan-center-index/issues/4751

**Comment by ericriff** [comment]
@madebr do you want to open a PR with https://github.com/madebr/conan-center-index/tree/sentry_breakpad
?
I want to play around with it locally, I can give you some feedback.

**Comment by madebr** [comment]
I've opened it in #5737

**Comment by perseoGI** [comment]
Hi there!
I was reviewing old issues...

In this PR https://github.com/conan-io/conan-center-index/issues/19675, sentry-crashpad and sentry-breakpad were removed as dependencies of sentry-native following senetry-native maintainer recommendations of not packaging internal dependencies.

Therefore, we may said that sentry-crashpad and sentry-breakpad recipes are deprecated, or at least, don't have a specific reason to be maintained anymore because I personally don't see how could this packages be used outside senetry-native.

For now, I'll close this issue!
Happy coding 🐸
