### ISSUE TITLE
[package] boost/1.74.0: won't link

### ISSUE THREAD

**Issue by bahlborn** [conan-io/conan-center-index#5156]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.74.0**
  * Operating System+version: **Windows 10 Pro 10.0.19042 Build 19042**
  * Compiler+version: **MSVC 2019 version 16.9.1**
  * Conan version: **conan 1.35.0**
  * Python version: **Python 3.9.1**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Using cmake_find_package generator and cmake find_package(Boost), the following error happens when linking:
LNK1104	cannot open file 'libboost_filesystem-vc142-mt-sgd-x64-1_74.lib'

**Comment by Nekto89** [comment]
Are you using "Boost::disable_autolinking"?

**Comment by bahlborn** [comment]
I don’t believe so. I am double checking with another member of the team who setup the project.

An additional piece of information; in the project where the link error occurred, we were linking Boost::headers. Changing this to Boost::Boost allows the project to link.

**Comment by bahlborn** [comment]
We are not explicitly setting it, but we do see a message in the output message “boost/1.74.0: Disabled magic autolinking (smart and magic decisions)”.

**Comment by helmesjo** [comment]
@Nekto89 Any ideas for this? Basically when "linking" the headers-only target `Boost::headers` it appears to still include link targets.
@madebr Since you did #2097 (which worked in this case when it was first merged), do you spot any oddities in recent changes? Since one doesn't necessarily clear the cache every day it's hard to tell when this started happening (and what commit that's possibly the culprit).

**Comment by madebr** [comment]
@helmesjo 

The `"Disabled magic autolinking (smart and magic decisions)"` message is emitted here:
https://github.com/conan-io/conan-center-index/blob/f42348714f2b877c0fa7919cddf48e804dbc2971/recipes/boost/all/conanfile.py#L1218-L1228

Try adding `add_definitions(BOOST_ALL_NO_LIB)` to the top of your cmake build script (after `project`).
It that works, then somehow the incorrect compile flags are passed to the compiler.

See https://www.boost.org/doc/libs/1_75_0/libs/config/doc/html/index.html#boost_config.configuring_boost_for_your_platform.user_settable_options for the available definitions.

**Comment by helmesjo** [comment]
@madebr With `add_definitions(-DBOOST_ALL_NO_LIB)` it doesn't fail on the missing lib so I guess your hypothesis is correct.
But now instead I get `unresolved symbols` pointing to `boost::filesystem` so it appears some header we use are still using functions from that lib.

**Comment by madebr** [comment]
All cmake targets that use boost's filesystem or are exposing boost filesystem through its headers must link to `Boost::filesystem`.
See https://cmake.org/cmake/help/latest/module/FindBoost.html#imported-targets for the available targets.

**Comment by helmesjo** [comment]
Thanks! Yeah, had to dig through the includes in `boost/process` to see that it reaches into `filesystem` (even though the error already suggested this), but it was hard to figure this one out since the documentation doesn't appear to explicitly say it (or I'm just poor at googling).

So basically `Boost::process` is a header-only lib that requires other non-header-only libs..? Linking `Boost::headers` & `Boost::filesystem` appears to be enough.

Now there is just the problem that linking only `Boost::headers` tricks CMake into automagically link non-existing libraries (wrong naming convention) I guess (but yes I can get around that for now by explicitly linking both `headers` & `filesystem`).

**Comment by madebr** [comment]
The current conanfile only passes these definitions (`BOOST_ALL_NO_LIB`) for the library components, not for the header component.
Maybe we should change this to add these defines to the header component.

Soon, boost 1.75.0 will be released.
I'll try to shove in this change.

**Comment by madebr** [comment]
I am now going through the boost recipe to add 1.76.0.
I will not make the change I suggested in [my previous comment](https://github.com/conan-io/conan-center-index/issues/5156#issuecomment-820510834)
The [FindBoost document](https://cmake.org/cmake/help/latest/module/FindBoost.html) suggests to use `Boost::disable_autolinking` to "disable automatic linking with MSVC (adds -DBOOST_ALL_NO_LIB)".

**Comment by SSE4** [comment]
need to link with `Boost::disable_autolinking` in order to disable auto-linking
