### ISSUE TITLE
[question] Add iOS/Android build support on CCI.

### ISSUE THREAD

**Issue by dmn-star** [conan-io/conan-center-index#537]
We have used Conan on Win/Linux for several years. Last year we ported our c++ libraries to iOS/Android. Conan was the only package manager that also worked for mobile platforms too.  Great job!  Maybe you want to extend this unique selling point and add iOS/Android to the list of supported platforms?

A very merry Christmas and a happy new year!

**Comment by Croydon** [comment]
To clarify: The list you can see [in the wiki](https://github.com/conan-io/conan-center-index/wiki/Supported-Platforms-And-Configurations) contains the targets for which we are building, providing and continuously testing the recipes

If you run into issues with the recipes for iOS and Android then feel free to open issues for this and/or open a pull request with a fix

**Comment by dmn-star** [comment]
I know the wiki. I mean the build service should build & test the recipes for Android/iOS too.

**Comment by uilianries** [comment]
@dmn-star As you know, some recipes are prepared to support iOS and Android because we have an amazing community, but it demands a lot of effort and is not general usage by most of users. To support only the 3 main platforms (windows, mac and linux), sometimes we took days to finish only one recipe, now imagine adding extra platforms ... Also, it will increase the CI, including storage. I don't believe we will support Android/iOS in short or middle term, because we don't have a big demand.

Thanks for your interest and happy holidays :santa:

**Comment by danimtb** [comment]
Thanks for the valuable info @dmn-star! I agree with the comments above. Making the recipes work in the 3 major platforms is not as easy as it seems and we can only provide support for that currently. Also, when cross-building for Android/iOS the toolchains can be different from one to another depending on their specific needs. Maybe we have to consider adding support in the future, but nor in the middle term.

**Comment by a4z** [comment]
I agree that the situation for is difficult, mabye split this into Android and iOS  , to make 2 problems instead of 1 huge one.

Android could be solved, since the Android NDK is available as a conan package, and with this in the latest version as default, Android could be added into to CI/CD pipeline. Maybe just as info, not making it failing a PR if it not builds.

It should be possible to provide a container for that, maybe I can make one once I have a bit extra time

iOS is difficult because you need a Mac, its not allowed to run that virtual, and even for downloading a xcode you need a valid apple account

**Comment by dmn-star** [comment]
CCI already supports macOS  iOS should not be a problem (if package supports iOS build).

**Comment by n-eq** [comment]
@dmn-star I'm facing the same issue, any updates?

**Comment by dmn-star** [comment]
Not really. Ongoing discussion is now here

**Comment by n-eq** [comment]
@dmn-star Thanks for the pointer. I mistakenly replied here instead of this issue https://github.com/conan-io/conan-center-index/issues/3625

**Comment by AbrilRBS** [comment]
With the advent of the new CI system, we're now capable of running more configurations, and we have Android planned for the future, stay tuned, and thanks a lot to everone who chimed in back then!
