### ISSUE TITLE
[request] qt/6.1.0

### ISSUE THREAD

**Issue by mjvankampen** [conan-io/conan-center-index#5518]
### Package Details
  * Package Name/Version: **qt/6.1.0**
  * Changelog: **https://www.qt.io/blog/qt-6.1-released**

New qt has been released. I'm not sure how to best handle the _submodules. I think it should be populated from the qtmodules6.x.x.conf.

What do you think @ericLemanissier

**Comment by ericLemanissier** [comment]
I don't expect populating _submodules from qtmodules.conf to work properly, because the version is not known when the class is loaded (this is the reason why I add to create this _submodules variable). I think the proper solution is to add all the new modules to `_submodules`, and then in `config_options` remove all the options in self.options and _submodules which are not present in qtmodulesX.Y.Z.conf

**Comment by yuriy-mochurad** [comment]
@ericLemanissier are there any plans to support this in the near future?
Would be nice to have it available.
Thank you for your support.
