### ISSUE TITLE
[package] prometheus-cpp: Build with more configurations

### ISSUE THREAD

**Issue by alejandro-colomar** [conan-io/conan-center-index#5565]
I'd like to have a version of prometheus-cpp with `prometheus-cpp:with_push=False`.  Right now I have to build it locally because all of the packages uploaded to conan-center have this flag as `True`.

I'm not sure how to change your code so that this configuration is also built (which I guess is possible).

Could you please help me prepare a PR for that?

**Comment by Croydon** [comment]
> which I guess is possible

Unfortunately, it is not, only the default options are built.

**Comment by alejandro-colomar** [comment]
Isn't it possible to use the same mechanism that you use for setting shared to `True` and `False` to also set other flags to `True` and `False`?

I see that eventhough the default is `shared:False`, you are also building `shared:True` packages.

**Comment by alejandro-colomar** [comment]
Or is it a policy of yours to avoid wasting space?

**Comment by prince-chrismc** [comment]
It's a technical limitation of CCI building option combinations would need to be *all or nothing* imagine trying to build all the combinations of boost... it does not scale well...

As i've understood, it's a dream feature but there's more pressing issues for the Conan team so hopefully one day

**Comment by alejandro-colomar** [comment]
There's another solution: what Debian does.

They produce many small binary packages from a single source package, so that the consumers can cherry-pick the specific features that they want.

That would mean the following packages, for example:

prometheus-cpp-core
prometheus-cpp-pull
prometheus-cpp-push

**Comment by alejandro-colomar** [comment]
Oops, closed by accident

**Comment by perseoGI** [comment]
Hi @alejandro-colomar,
I was reviewing old issues and I have come across this one.

As @prince-chrismc explained (years ago), we still have nowadays a CI limitation. We are only building packages with the default options (and yes, we build both combinations of shared=True/False, in a multi OS with a multi compiler types and versions).
Imagine the cost of our CI, spoiler, is huge. Really enormous.

We may expect in the nearby future, when `conan v1` gets officially deprecated to build bigger matrix combinations. 
But for the moment, it is still a "conan-dream".

Also, what you described about what Debian does by building small binaries is what we do at Conan. We build multiple binaries and conan client is in charge of downloading the compatible version which matches your profile specification.

I'm closing this issue due to its impossibility, but we are aware of your concerns and we are actually working on a new CI which will enhance contributor experience!

Happy coding 🐸
