### ISSUE TITLE
[package] libtiff/4.2.0: Fails to build with GCC11/Cmake 3.20

### ISSUE THREAD

**Issue by twantonie** [conan-io/conan-center-index#5587]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: libtiff/4.2.0
  * Operating System+version: Arch linux
  * Compiler+version: GCC 11
  * Conan version: 1.37.0-dev
  * Python version: 3.9.5
  * Cmake version: 3.20.2

### Conan profile
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce
Tried to build libtiff using the standard `--build missing` which came up with the errors in configure_fail1.txt. Deleting /usr/lib64/cmake/libjpeg-turbo/libjpeg-turboConfig.cmake included from Cmake allowed me to build libtiff.

### Logs
[configure_fail1.txt](https://github.com/conan-io/conan-center-index/files/6519047/configure_fail1.txt)

**Comment by madebr** [comment]
[libtiff applies a patch](https://github.com/conan-io/conan-center-index/blob/1787ab2577ac7d8396c9ae741cb2e9e6defe187e/recipes/libtiff/all/patches/4.2.0-0001-cmake-add-libjpeg-turbo.patch) in order to enable switching between libjpeg and libjpeg-turbo (libtiff has a ` "jpeg": [False, "libjpeg-turbo", "libjpeg"],` option).

A `find_package` call with only a name should not fail when `REQUIRED` is not an argument (this approach is error prone though).

I just tried building libtiff on my system and cannot reproduce your error.
[log_shared.txt](https://github.com/conan-io/conan-center-index/files/6519278/log_shared.txt)
[log_static.txt](https://github.com/conan-io/conan-center-index/files/6519290/log_static.txt)
The warning is expected. But it's not promoted to an error.

Please run `conan config set log.print_run_commands=True` and  provide a complete `conan create . libtiff/4.2.0@ >log.txt 2>&1` build trace.
Maybe it contains a smoking gun.

**Comment by twantonie** [comment]
I couldn't get `conan create . libtiff/4.2.0@` to work in the conan-index, [conan_index_log.txt](https://github.com/conan-io/conan-center-index/files/6519386/log.txt). But I figured out where the error comes from [log.txt](https://github.com/conan-io/conan-center-index/files/6519378/log.txt), libjpeg-turbo is installed on my system and it's find_package is broken. 

Thanks for your input

**Comment by madebr** [comment]
I just added libtiff 4.3.0 in https://github.com/conan-io/conan-center-index/pull/5590
I made the build script robust(er) against system libjpeg(-turbo) libraries (only for 4.3.0).

It would be nice if you could test whether it fixes your original problem.

**Comment by twantonie** [comment]
That fixed the original issue

**Comment by madebr** [comment]
Thanks for the double check!
