### ISSUE TITLE
[package] fontconfig/2.13.93: How to use with sysconfdir set on build machine

### ISSUE THREAD

**Issue by hobbeshunter** [conan-io/conan-center-index#5782]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **fontconfig/2.13.93**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9.3.0**
  * Conan version: **conan 1.36.0**
  * Python version: **Python 3.8.5**

### Conan profile
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Currently I'm trying to build an app with Qt6. When I run the app I get the error 
```
Fontconfig error: Cannot load default config file: No such file: (null)
```
When investigating this with strace I found that fontconfig looks at 
```
/home/conan/w/BuildSingleReference/.conan/data/fontconfig/2.13.93/_/_/package/211285f7c5eb7915075b241bd6a053e345cec58c/bin/etc/fonts/fonts.conf
```

which seems to come from the way sysconfdir is defined in the recipe: https://github.com/conan-io/conan-center-index/blob/38d85e32c8352c7faabf191901ac126ec1214f95/recipes/fontconfig/all/conanfile.py#L61

Of course this behavior can be avoided by setting the environment variable `FONTCONFIG_PATH`.

As I want my app easily distributable through conan, what is the recommended way to hint fontconfig to the right path (e.g. `/etc/fonts` on Ubuntu)?

Thanks in advance!

**Comment by rockdreamer** [comment]
This issue affects me too, our applications look.. less that stellar due to use of base X11 fonts on linux

**Comment by paulharris** [comment]
I'm thinking a package option might be an approach.
Then you build for a target platform, but now it is up to every conan user to build fontconfig with the right paths compiled in ...
Still better than asking the user to set an env variable, or have to drop scripts to run binaries to set the env.

**Comment by uilianries** [comment]
Usually we install those extra files in `package_folder/res`, then people can redistribute as they want by [imports](https://docs.conan.io/en/latest/reference/conanfile_txt.html#imports) or [deploy](https://docs.conan.io/en/latest/reference/generators/deploy.html). Conan is not focused in deploying artifacts ...

The `FONTCONFIG_PATH` is already configured on that recipe at [line 112](https://github.com/conan-io/conan-center-index/blob/38d85e32c8352c7faabf191901ac126ec1214f95/recipes/fontconfig/all/conanfile.py#L112), which means, it should for you, if you are using Conan to build your app. Otherwise, you can use the [virtualenv](https://docs.conan.io/en/latest/mastering/virtualenv.html#virtualenv-generator) generator.

**Comment by ericLemanissier** [comment]
Actually the main problem is that you usually want to use the system configuration files, not the ones packaged by conan. This makes the look of your app consistent with the rest of the OS

**Comment by hobbeshunter** [comment]
Thanks @uilianries for mentioning virtualenv. I did not think of it in that context. But since conf.d is empty in the package this doesn't change anything. Qt apps look pretty bad without a proper font (as @paulharris is saying).

In one of my projects I therefore started to treat fontconfig as system package and wrote a recipe that uses `tools.SystemPackageTool` to install it. See https://github.com/hobbeshunter/ConanQtOSGDemo/blob/59ecb9cae01a127f4b46105f4769cde4aa0ec946/fontconfig_conanfile.py. For now it only tested it on Ubuntu.

**Comment by paulharris** [comment]
I'm thinking of adding a fontconfig flag to tell the recipe to use /etc/fonts etc instead of the conan-cache ones.
I figure that would do the job, and I don't have to set the environment up every time I run the program.

**Comment by baron1405** [comment]
@paulharris I hit this issue today and was wondering if there has been any progress allowing the build to reference the platform font config directory.

**Comment by paulharris** [comment]
Not to my knowledge, I still would like to see this progressed but am
waiting for v2 to land.

In the meantime, I'm expecting to have to hard wire an environmental
variable into a script to run my programs, or put it into main() somehow.

**Comment by baron1405** [comment]
@paulharris Thanks for getting back to me. I have a Qt app and put this in my main before instantiating the application object:
```
qputenv("FONTCONFIG_PATH", "/etc/fonts");
```
It works and should be stable across distros. In my deb spec I will require the fontconfig package, which is not unreasonable for a GUI app.

**Comment by paulharris** [comment]
Great tip! Thanks very much!

**Comment by paulharris** [comment]
Note for others, I had previously found I had to specify all these in the env:
```
export FONTCONFIG_FILE=/etc/fonts/fonts.conf
export FONTCONFIG_PATH=/etc/fonts
export XLOCALEDIR=/usr/share/X11/locale
```

**Comment by uilianries** [comment]
I would suggest configuring those variables directly in your profile, it will be much safer and reproducible:

```
...

[runenv]
FONTCONFIG_PATH=/etc/fonts
FC_TEMPLATEDIR=/usr/share/fontconfig/conf.avail
FC_CACHEDIR=/var/cache/fontconfig
CONFIGDIR=/etc/fonts/conf.d
```

Even if the recipe configure those variables, Conan will prioritize what's in your profile.

https://docs.conan.io/2/reference/config_files/profiles.html#runenv

**Comment by paulharris** [comment]
And how does that work when you try and deploy the app?
At the moment, I have to workaround this by adding code to the start of my program that sets these environment variables.
ie using `qputenv("FONTCONFIG_PATH", "/etc/fonts")` -- using QT's function.

I'm setting:
`FONTCONFIG_PATH=/etc/fonts`
`FONTCONFIG_FILE`/etc/fonts/fonts.conf`
`XLOCALDIR=/usr/share/X11/locale`

I didn't know about FC_TEMPLATEDIR  FC_CACHEDIR  CONFIGDIR

**Comment by uilianries** [comment]
> And how does that work when you try and deploy the app?

@paulharris could you elaborate more about this? Probably I'm missing something, because `fontconfig` would use `FONTCONFIG_PATH` variable configured by Conan envs.

**Comment by paulharris** [comment]
The program and its dlls and other files are all packaged up and
distributed as an installable deb for ubuntu/debian computers (and msi for
Windows).   Conan runenv is not going to help there... Right?

**Comment by uilianries** [comment]
Closing this issue, as I believe the previous comment https://github.com/conan-io/conan-center-index/issues/5782#issuecomment-2161050812 mitigates the matter in question. 

Please, feel free to give your feedback.

**Comment by Osse** [comment]
@uilianries: I have gotten the alternative approach of using extra machine files to work. Thanks!

However modifying the package ID as suggested does not work in our case because the package ID will be different from one developer's computer to the next. Using a relative path in `tools.meson.mesontoolchain:extra_machine_files` breaks the Meson build. Using an absolute path leads to the value of the option to be different leading to different package IDs (it seems the package ID is calculated after jinja2 has processed the profile, reasonably enough).

I haven't been able to find a fix for this. But on the other hand it is very unlikely we would ever want to change the contents of the file so it is not a deal breaker.

**Comment by uilianries** [comment]
> However modifying the package ID as suggested does not work in our case because the package ID will be different from one developer's computer to the next

@Osse Hello!

That's expected because the path will be hardcoded in the package well. It does not differ from having an option: An option will affect the package ID as well. 

> Using a relative path in tools.meson.mesontoolchain:extra_machine_files breaks the Meson build

I would suggest you open an issue to https://github.com/conan-io/conan in case it is something supposed to be supported by Meson.
