### ISSUE TITLE
[package] tbb/2020.3: missing architecture for armv7hf

### ISSUE THREAD

**Issue by yuriy-mochurad** [conan-io/conan-center-index#5789]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: tbb/2020.3
  * Operating System+version: Cross compiling in docker image https://hub.docker.com/r/conanio/gcc10-armv7hf/
  * Compiler+version: gcc 10
  * Docker image: conanio/gcc10-armv7hf
  * Conan version: 1.35.2
  * Python version: Python 3.7.4

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=armv7hf
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: tbb/2020.3: Error in build() method, line 127

	}[str(self.settings.arch)]

	KeyError: 'armv7hf'
```

</details>

It looks like conanfile is missing the mapping for armv7hf around these lines: https://github.com/conan-io/conan-center-index/blob/master/recipes/tbb/all/conanfile.py#L125

**Comment by perseoGI** [comment]
Hi there!
I was reviewing old issues and found this one.

Conan version in [hub.docker.com/r/conanio/gcc10-armv7hf](https://hub.docker.com/r/conanio/gcc10-armv7hf/) did not have support for `armv7hf` but newer conan version does.

I'm closing this issue as this `tbb` recipe has been modified multiple times since 2021. 
If this problem remains nowadays, do not hesitate to reopen this issue and add new traces, preferably using `conan v2`.

Happy coding 🐸
