### ISSUE TITLE
[package] qt/6.1.0: optional dependancies are not ignored.

### ISSUE THREAD

**Issue by DhruvParanjape** [conan-io/conan-center-index#5853]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **zlib/1.2.8**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 8**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.18.0**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Put your profile output here
```

### Steps to reproduce (Include if Applicable)
build qt 6.1.0 with qtquickcontrols2

need to patch the release with https://github.com/qt/qt5/commit/81096b44bb183772c979debca2ffd1f8b364bbc8#diff-06b0e3ecde28a73b4fdf20beed47550bbfbab5cf0d6ae8c5372fd996ffb3ab68

which fixes bug QTBUG-91144

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by ericLemanissier** [comment]
I'm afraid you will have to wait for qt 6.2.0 to see this bug solved, cf https://github.com/conan-io/conan-center-index/pull/3951

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.
The `qt/6.1.0` version is no longer supported by Conan Center Index.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported.
If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
