### ISSUE TITLE
[package] glog/<any>: glog ABI depends on gflags:nothreads

### ISSUE THREAD

**Issue by alex-700** [conan-io/conan-center-index#5901]
Hi! Sorry for non-formatted bug report.

- `glog` depends on `gflags`
- `gflags` has the option `nothreads`, which changes a name of library (`gflags` vs `gflags_nothreads`)
- `glog` has no special actions in the recipe for defining a right ABI compatibility. It seems that the `glog` recipe needs a custom `package_id`, where it will consider a value of `gflags:nothreads` somehow.

tag @SpaceIm as the last person, who refactors `glog` recipe.

**Comment by perseoGI** [comment]
Hi @alex-700 
I was reviewing old issues and I have come across this one.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported.
Concretely, this one https://github.com/conan-io/conan-center-index/pull/12909/files#diff-ae759f222aa289abc0e1d63fc193927641705450b304c9adff810512a163a33fR101 aims to fix your `gflags:nothreads` issue.

If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
