### ISSUE TITLE
[package] sentry-crashpad is building internal chechout of lss instead of the Conan package

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#6295]
sentry-crashpad sources contain a copy of linux-syscall-support.h
This header is packaged with conan and used as a dependendency for other packages.

The recipe should ditch the internal copy of lss in favour of the one packaged by Conan.

**Comment by perseoGI** [comment]
Hi there!
I was reviewing old issues...

In this PR https://github.com/conan-io/conan-center-index/issues/19675, `sentry-crashpad` and `sentry-breakpad` were removed as dependencies of `sentry-native` following `senetry-native` maintainer recommendations of not packaging internal dependencies. 

Therefore, we may said that `sentry-crashpad` and `sentry-breakpad` recipes are deprecated, or at least, don't have a specific reason to be maintained anymore because I personally don't see how could this packages be used outside `senetry-native`.

If you have a clue or a suggestion please do not hesitate to respond in here.
For now, I'll close this issue!
Happy coding 🐸
