### ISSUE TITLE
[package] llvm-core/12.0.0: Missing LibXML2 while building.

### ISSUE THREAD

**Issue by tcanabrava** [conan-io/conan-center-index#6433]
While trying to compile llvm-core/12.0.0 on mac:

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **llvm-core/12.0.0**
  * Operating System+version: **Mac OS 11.4**
  * Compiler+version: **GCC 8**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.38.0**
  * Python version: **Python 3.9.6**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
➜  diagram-server conan profile show default
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
create a small conanfile with llvm-core/12.0.0 and trigger a build

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```

llvm-core/12.0.0: Generator cmake_find_package created FindLibXml2.cmake
...
CMake Error at /Users/bl029-user/.conan/data/llvm-core/12.0.0/_/_/build/3575379c3e144431cab8dad8de983e587812fef2/CMakeFiles/CMakeTmp/CMakeLists.txt:10 (include_directories):
  Error evaluating generator expression:

    $<TARGET_PROPERTY:LibXml2::LibXml2,INTERFACE_INCLUDE_DIRECTORIES>

  Target "LibXml2::LibXml2" not found.
```
</details>

**Comment by madebr** [comment]
@SpaceIm 
I think my suggestion at https://github.com/conan-io/conan-center-index/pull/6303#discussion_r669899265 is causing problems.
The cmake script of llvm is probably doing a call to [`check_cxx_source_compiles`](https://cmake.org/cmake/help/latest/module/CheckCXXSourceCompiles.html) (or similar) with `CMAKE_REQUIRED_INCLUDES` set to `${LIBXML2_INCLUDE_DIRECTORIES}`, that contains `$<TARGET_PROPERTY:LibXml2::LibXml2,INTERFACE_INCLUDE_DIRECTORIES>`.

Internally, `check_cxx_source_compiles` creates a dummy cmake project with some basic variables set.
The error comes from the dummy cmake project: the target `LibXml2::LibXml2` does not exist there.

**Comment by SpaceIm** [comment]
I see, do you want to open a PR? I think that `xapian-core` recipe is a good starting point to create a less fragile module file working with cmake_find_package and cmake_find_package_multi.

**Comment by madebr** [comment]
How about the following?:
The current `xapian-core` recipe contains:
```cmake

            set(XAPIAN_FOUND TRUE)
            set(XAPIAN_INCLUDE_DIR ${xapian_INCLUDE_DIR}
                                   ${xapian_INCLUDE_DIR_RELEASE}
                                   ${xapian_INCLUDE_DIR_RELWITHDEBINFO}
                                   ${xapian_INCLUDE_DIR_MINSIZEREL}
                                   ${xapian_INCLUDE_DIR_DEBUG})
            set(XAPIAN_LIBRARIES ${xapian_LIBRARIES}
                                 ${xapian_LIBRARIES_RELEASE}
                                 ${xapian_LIBRARIES_RELWITHDEBINFO}
                                 ${xapian_LIBRARIES_MINSIZEREL}
                                 ${xapian_LIBRARIES_DEBUG})
```
Do this instead?
```cmake

            set(XAPIAN_FOUND TRUE)
            set(XAPIAN_INCLUDE_DIR ${xapian_INCLUDE_DIR}
                                   $<$<CONFIG:Release>:${xapian_INCLUDE_DIR_RELEASE}>
                                   $<$<CONFIG:RelWithDebInfo>:${xapian_INCLUDE_DIR_RELWITHDEBINFO}>
                                   $<$<CONFIG:MinSizeRel>:${xapian_INCLUDE_DIR_MINSIZEREL}>
                                   $<$<CONFIG:Debug>:${xapian_INCLUDE_DIR_DEBUG}>)
            set(XAPIAN_LIBRARIES ${xapian_LIBRARIES}
                                 $<$<CONFIG:Release>:${xapian_LIBRARIES_RELEASE}>
                                 $<$<CONFIG:RelWithDebInfo>${xapian_LIBRARIES_RELWITHDEBINFO}>
                                 $<$<CONFIG:MinSizeRel>${xapian_LIBRARIES_MINSIZEREL}>
                                 $<$<CONFIG:Debug>${xapian_LIBRARIES_DEBUG}>)
```
Perhaps we can create a template to ease this?

**Comment by SpaceIm** [comment]
If it works with `check_cxx_source_compiles`, it's fine for me ;)

**Comment by madebr** [comment]
I am looking at libxml2, but it is more complicated than I feared.
To get e.g. `check_c_source_compiles` working, we need to provide *pure* cmake variables (=no generator expressions depending on targets).

But a generated `LibXml2Config.cmake` file is including our custom `LibXml2Targets.cmake` before creating any target, before including the config files for all build types and before executing `find_package` for all dependencies.
So currently, I don't see a way to create these variables.

For libxml2, using cmake_find_package_multi generator, we have
1. include custom cmake scripts
2. create LibXml2::LibXml2 target
3. add information for all build types to the target
4. find all dependencies
```

So using `get_target_property` becomes impossible as well.
I think this is a conan bug/missing feature.

2 thing are needed:
1. the generators should create pure cmake variables (for each build type) that includes information for dependencies as well
2. recipe provided cmake scripts should be executed at the end. That way, a user can override automatic variables + access targets/variables.

I double this change will ever happen because `cmake_find_package`/`cmake_find_package_multi` will be deprecated in cmake 2.

**Comment by madebr** [comment]
I am looking at libxml2, but it is more complicated than I feared.
To get e.g. `check_c_source_compiles` working, we need to provide *pure* cmake variables (=no generator expressions depending on targets).

But a generated `LibXml2Config.cmake` file is including our custom `LibXml2Targets.cmake` before executing `find_package` for all dependencies.
So currently, I don't see a way to include this into the variables.

For libxml2, using cmake_find_package_multi generator, we have
1. create LibXml2::LibXml2 target
2. add information for all build types to the target
3. include custom cmake scripts
4. find all dependencies

So using `get_target_property` becomes impossible as well.
I think this is a conan bug/missing feature.

2 thing are needed:
1. the generators should create pure cmake variables (for each build type) that includes information for dependencies as well
2. recipe provided cmake scripts should be executed at the end. That way, a user can override automatic variables + access targets/variables.

I doubt this change will ever happen because `cmake_find_package`/`cmake_find_package_multi` will be deprecated in conan 2.

See [the libxml2_no_genexp_in_vars branch on my fork](https://github.com/madebr/conan-center-index/tree/libxml2_no_genexp_in_vars) for a reproducer of this problem.

(In a previous version of this comment, I erroneously thought that the custom scripts were executed at the beginning)

**Comment by madebr** [comment]
The [llvm-core error is emitted here](https://github.com/llvm/llvm-project/blob/ffe32b5c71bfea0009e6d8d1788971d237709672/llvm/cmake/config-ix.cmake#L149-L154).

I've toyed a bit with [`try_compile`](https://cmake.org/cmake/help/latest/command/try_compile.html) ([`check_symbol_exists`](https://cmake.org/cmake/help/latest/module/CheckSymbolExists.html) uses `try_compile` under the hood)
It is possible to use imported cmake targets with `try_compile`, generated by `cmake_find_package`.
But imported cmake targets, generated by `cmake_find_package_multi` are not compatible.

To see this problem in in cmake's perspective: what build_type should be used for the test in `try_compile`?

For fixing the libxml2 problem, I would just pass through the cmake imported target.
I've toyed a bit with letting the `cmake_find_package`(`_multi`) generator create pure cmake variables (without targets).
But finally, `cmake_find_package_multi` has the same problem as described above. 

Noteworthy is that the current `cmake_find_package` generator puts imported targets in the `LibXml2_LIBRARIES` cmake variable. This make the `cmake_find_package` generator only compatible with cmake versions >= 3.0.

@tcanabrava 
Try applying the following patch to the current libxml2 recipe, rebuild the libxml2 package, and try rebuilding llvm-core.
```patch
diff --git a/recipes/libxml2/all/conanfile.py b/recipes/libxml2/all/conanfile.py
index 711dee40e..6f689a4b8 100644
--- a/recipes/libxml2/all/conanfile.py
+++ b/recipes/libxml2/all/conanfile.py
@@ -250,11 +250,11 @@ class Libxml2Conan(ConanFile):
         # FIXME: also define LIBXML2_XMLLINT_EXECUTABLE variable
         content = textwrap.dedent("""\
             set(LIBXML2_FOUND TRUE)
-            set(LIBXML2_INCLUDE_DIR $<TARGET_PROPERTY:LibXml2::LibXml2,INTERFACE_INCLUDE_DIRECTORIES>)
-            set(LIBXML2_INCLUDE_DIRS ${{LIBXML2_INCLUDE_DIR}})
-            set(LIBXML2_LIBRARIES $<LINK_ONLY:LibXml2::LibXml2>)
-            set(LIBXML2_LIBRARY ${{LIBXML2_LIBRARIES}})
-            set(LIBXML2_DEFINITIONS $<TARGET_PROPERTY:LibXml2::LibXml2,INTERFACE_COMPILE_DEFINITIONS>)
+            set(LIBXML2_INCLUDE_DIR ${{LibXml2_INCLUDE_DIR}})
+            set(LIBXML2_INCLUDE_DIRS ${{LibXml2_INCLUDE_DIRS}})
+            set(LIBXML2_LIBRARIES LibXml2::LibXml2)
+            set(LIBXML2_LIBRARY LibXml2::LibXml2)
+            set(LIBXML2_DEFINITIONS ${{LibXml2_DEFINITIONS}})
             set(LIBXML2_VERSION_STRING "{major}.{minor}.{patch}")
         """.format(major=version.major, minor=version.minor, patch=version.patch))
         tools.save(module_file, content)
diff --git a/recipes/libxml2/all/test_package/CMakeLists.txt b/recipes/libxml2/all/test_package/CMakeLists.txt
index ef5697dfd..755f3497a 100644
--- a/recipes/libxml2/all/test_package/CMakeLists.txt
+++ b/recipes/libxml2/all/test_package/CMakeLists.txt
@@ -4,7 +4,7 @@ project(test_package C)
 include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
 conan_basic_setup(TARGETS)
 
-find_package(LibXml2 REQUIRED)
+find_package(LibXml2 REQUIRED MODULE)
 message("LIBXML2_FOUND: ${LIBXML2_FOUND}")
 message("LIBXML2_INCLUDE_DIR: ${LIBXML2_INCLUDE_DIR}")
 message("LIBXML2_INCLUDE_DIRS: ${LIBXML2_INCLUDE_DIRS}")
@@ -13,5 +13,22 @@ message("LIBXML2_LIBRARY: ${LIBXML2_LIBRARY}")
 message("LIBXML2_DEFINITIONS: ${LIBXML2_DEFINITIONS}")
 message("LIBXML2_VERSION_STRING: ${LIBXML2_VERSION_STRING}")
 
+# Test whether the cmake variables can be used in CheckXXX modules.
+include(CheckCSourceCompiles)
+set(CMAKE_REQUIRED_DEFINITIONS "${LIBXML2_DEFINITIONS}")
+set(CMAKE_REQUIRED_INCLUDES "${LIBXML2_INCLUDE_DIRS}")
+set(CMAKE_REQUIRED_LIBRARIES "${LIBXML2_LIBRARIES}")
+check_c_source_compiles([=[
+#include <libxml/parser.h>
+int main() {
+    xmlDoc *doc = NULL;
+    xmlDocGetRootElement(doc);
+    return 0;
+}
+]=] HAS_XMLDOCGETROOTELEMENT)
+if(NOT HAS_XMLDOCGETROOTELEMENT)
+    message(FATAL_ERROR "Test compilation of source using libxml2 failed.")
+endif()
+
 add_executable(${PROJECT_NAME} test_package.c)
 target_link_libraries(${PROJECT_NAME} LibXml2::LibXml2)
```

Because `llvm-core` uses the `cmake_find_package` generator, it should work.

**Comment by tcanabrava** [comment]
@madebr I will, can you provide me a bit of info on how to do that? my conan knowledge is quite small.
I just create a conanfile.txt and try to conan install things.

As soon as I understand a bit more about the intrinsics of conan, I'll stop opening bug reports and will send merge requests instead.
