### ISSUE TITLE
[request] <Exiv2>/<0.27.4>

### ISSUE THREAD

**Issue by ryanseipp** [conan-io/conan-center-index#6584]
### Package Details
  * Package Name/Version: **Exiv2/0.27.4**
  * Website: **https://exiv2.org/index.html**
  * Source code: **https://github.com/Exiv2/exiv2**

### Description Of The Library / Tool
Exiv2 is a Cross-platform C++ library and a command line utility to manage image metadata. It provides fast and easy read and write access to the Exif, IPTC and XMP metadata and the ICC Profile embedded within digital images in various formats. Exiv2 is available as free software and is used in many projects including KDE and Gnome Desktops as well as many applications including GIMP, darktable, shotwell, GwenView and Luminance HDR.

**Comment by theirix** [comment]
exiv2 has Conan support in upstream - https://github.com/Exiv2/exiv2/blob/main/README-CONAN.md
Do we need to have it in CCI? I prepared a draft PR for exiv2 that has fine-grained options (no curl if not needed) and relies more on CCI packages rather than other repositories (it uses `xmp` from another repository for example).

Do we have a rule about repackaging such packages - bring them to CCI or improve upstream support?

**Comment by SpaceIm** [comment]
Internal conan support of a library is orthogonal, just ignore it when packaging for CCI.
