### ISSUE TITLE
[package] xorg/system: missing system dependencies from recipe?

### ISSUE THREAD

**Issue by peter-moran** [conan-io/conan-center-index#6883]
### Package and Environment Details
  * Package Name/Version: **xorg/system**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0**
  * Docker image: **internal image based on `ubuntu:18.04`**
  * Conan version: **conan 1.33.0**
  * Python version: **Python 3.6.9**

### Conan profile
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce
While running `conan install` for my project, which depends on `qt/5.15.2` which depends on `xorg/system`, I got a ton of errors such as below, saying `Package X was not found in the pkg-config search path`. To get the install to work, I had to manually run/install the following:
```
apt-get update
apt-get install -y libfontenc-dev
apt-get install -y libxaw7-dev
apt-get install -y libxkbfile-dev
apt-get install -y libxmuu-dev
apt-get install -y libxres-dev
apt-get install -y libxss-dev
apt-get install -y libxv-dev
apt-get install -y libxvmc-dev
apt-get install -y libxcb-xkb-dev
apt-get install -y libxcb-icccm4-dev
apt-get install -y libxcb-image0-dev
apt-get install -y libxcb-keysyms1-dev
apt-get install -y libxcb-render-util0-dev
apt-get install -y libxcb-xinerama0-dev
apt-get install -y libxcb-util-dev libxcb-util0-dev
```
After doing this, the errors went away. It seems like these system installs might be missing from the recipe?

### Logs
<details><summary>Click to expand log</summary>

```
ERROR: xorg/system: Error in package_info() method, line 90
        self._fill_cppinfo_from_pkgconfig(name)
while calling '_fill_cppinfo_from_pkgconfig', line 24
        if not pkg_config.provides:
        ConanException: pkg-config command ['pkg-config', '--print-provides', 'xcb-xinerama', '--print-errors'] failed with error: Command 'pkg-config --print-provides xcb-xinerama --print-errors' returned non-zero exit status 1.
Package xcb-xinerama was not found in the pkg-config search path.
Perhaps you should add the directory containing `xcb-xinerama.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xcb-xinerama' found
```

</details>

**Comment by ericLemanissier** [comment]
if you want conan to install system packages for you, [you need to set environment variable `CONAN_SYSREQUIRES_MODE=enabled`](https://docs.conan.io/en/latest/reference/env_vars.html#conan-sysrequires-mode)

**Comment by peter-moran** [comment]
I already had `CONAN_SYSREQUIRES_MODE=enabled`. Additionally, if you look at the recipe, you will see the packages I had to install are not listed for Linux systems using `apt`.

https://github.com/conan-io/conan-center-index/blob/6a836859ffd401ca7fb3725900d542d9382d20d8/recipes/xorg/all/conanfile.py#L47

**Comment by ericLemanissier** [comment]
please

1. upgrade conan
2. run `rm -rf ~/.conan/data/xorg/`
3. uninstall all the packages you installed manually
4. run `CONAN_SYSREQUIRES_MODE=enabled conan install xorg/system@`

All the system packages should be properly installed, and the test should pass.
If after this, you manually uninstall one of the system packages, and just run `CONAN_SYSREQUIRES_MODE=enabled conan install xorg/system@`, then it's true that it won't install the missing package, because conan caches what was already installed. this cache can be deleted by running `conan remove --system-reqs */*@`

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.

I'm closing this issue as the problem was related with `conan v1` cache. 
`CONAN_SYSREQUIRES_MODE` variable is no longer required in `conan v2`

If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
