### ISSUE TITLE
[question] How to create receipt for complex package like OpenVINO

### ISSUE THREAD

**Issue by redradist** [conan-io/conan-center-index#7277]
Hi everyone,

I am curious is there a way to create package for [OpenVINO](https://github.com/openvinotoolkit/openvino) with lots of build dependencies on Ubuntu ...

Consider this list of dependencies https://github.com/openvinotoolkit/openvino/blob/master/install_build_dependencies.sh#L22

Some of the are available in conan-center, some of them are not ...

What is better to add all of them in `self.cpp_info.system_libs` or to create dependency `self.requires(...)` on some of the packages ?

**Comment by redradist** [comment]
Hi @madebr, do you know how properly to create package for this toolkit ?

**Comment by madebr** [comment]
If you want to do it "right", I would check out the openvino repo on my linux machine and patch it such that it can switch between system dependencies or vendored libraries.
e.g. by doing:
```cmake
option(OPENVINO_ZLIB_SYSTEM "Use system zlib library" OFF)
if(OPENVINO_ZLIB_SYSTEM)
    find_package(ZLIB REQUIRED)
else()
    if(NOT TARGET ZLIB::ZLIB)
        add_subdirectory(zlib EXCLUDE_FROM_ALL)
        add_library(ZLIB::ZLIB ALIAS zlib)  # <- I don't know what target the vendored zlib library actually creates
        endif()
endif()
```
Also, make sure that all openvino libraries use these targets.
If you suffer from visibility problems due to the [`GLOBAL` arg of `find_library(IMPORTED`](https://cmake.org/cmake/help/latest/command/add_library.html#imported-libraries), then you might need to do `include(cmake/thirdparty.cmake)` instead of `add_subdirectory(thirdparty)`.
Ideally, the result of this work can be upstreamed.


The dirty way is removing the `add_subdirectory(thirdparty)` and replace every use of a thirdparty library with a `find_package(DEP)` + modify the `target_link_libraries`.

**Comment by redradist** [comment]
@madebr One possible solution could be to deliver a binary package as it was done for `wasmtime` ...

Otherwise receipt for OpenVINO could be very complex and require to add lots of dependencies to `conan-center-index` for third-party libraries ...

**Comment by madebr** [comment]
We allowed wasmtime binaries because we don't have a rustlang compiler + packages for all its (cargo) dependencies.
openvino provides sources and no binaries.
We wouldn't allow openvino binaries either way. It would cause a lot of potential problems when vendored libraries collide with cci libraries.
openvino is an usual c/c++ library that should be buildable by c3i.
99.9% of the time, we only allow builds from source as these are the most flexible for users.

Looking at the thirdparty library, I think only 4 libraries are missing from cci: fluid, itt_collector, ittapi and opencl-clhpp-headers.
That doesn't sound too bad?

**Comment by redradist** [comment]
> 
> 
> We allowed wasmtime binaries because we don't have a rustlang compiler + packages for all its (cargo) dependencies.
> openvino provides sources and no binaries.
> We wouldn't allow openvino binaries either way. It would cause a lot of potential problems when vendored libraries collide with cci libraries.
> openvino is an usual c/c++ library that should be buildable by c3i.
> 99.9% of the time, we only allow builds from source as these are the most flexible for users.
> 
> Looking at the thirdparty library, I think only 4 libraries are missing from cci: fluid, itt_collector, ittapi and opencl-clhpp-headers.
> That doesn't sound too bad?

@madebr No, it sound good !!
Strange ... How have you investigated missed libraries ?

I've checked https://github.com/openvinotoolkit/openvino/blob/master/install_build_dependencies.sh#L22 ...
Seems like you've analyzed `find_package`-s ?

**Comment by madebr** [comment]
I only looked at the `thirdparty` folder and searched in the `recipes` folder of this repo whether a recipe was available.
It is entirely possible I missed a few libraries...

**Comment by prince-chrismc** [comment]
All the advice above is great, I would like to add a few of my own tricks

- CMake has a limited number of way to link to a lib (`find_library`, `find_package`, `target_link_library` are the main ones) which I typically search for on GitHub or with `grep`
- On large projects like this... absolutely make sure to kill the test and doc and samples... they always add complexity which is easier to avoid.
- Work in a minimal container... dev systems tend to have a lot in them so it's best to avoid CCI finding missing deps it's harder to repo

Then it's just a matter of tracing down undefined symbols or missing headers

**Comment by AvishekParajuli** [comment]
Did someone create  this openvino conan package?

**Comment by sbudenkov** [comment]
> Did someone create this openvino conan package?

Yes, we did it for internal needs using release SDK package.
