### ISSUE TITLE
[package] approvaltests.cpp:/8.1.0: Missing details on package web page

### ISSUE THREAD

**Issue by claremacrae** [conan-io/conan-center-index#768]
### Package and Environment Details (include every applicable attribute)
  * Not applicable - it's a web page problem

### Steps to reproduce (Include if Applicable)

* View the page https://bintray.com/conan/conan-center/approvaltests.cpp%3A_#
* At the time of writing, none of "About This Package" has any values, except "VCS" which says "None"
* Note that the recipe does have values for many of these fields: https://github.com/conan-io/conan-center-index/blob/9e731db1dcdf562197e1326e03702de6d2f70860/recipes/approvaltests.cpp/all/conanfile.py#L5-L13

**Question:** What needs to be done to pull this information from the conanfile.py?

(I've compared this recipe with the imgui one and can't see what difference matters...)

* https://github.com/conan-io/conan-center-index/tree/master/recipes/approvaltests.cpp
* https://github.com/conan-io/conan-center-index/tree/master/recipes/imgui

**Comment by claremacrae** [comment]
Screenshot: 
![2020-02-03 09 40 06 bintray com a208629f3723](https://user-images.githubusercontent.com/4840096/73642240-40bf2300-4669-11ea-8976-4d8834f83e01.png)

**Comment by uilianries** [comment]
Hi @claremacrae thanks for reporting. This case is also a feature request, since such integration requires Bintray API too. We have a Conan hook which is able to update the Bintray page, but it's not yet integrated with Conan Center Index.

Instead, you can use Conan Center search page: https://conan.io/center/approvaltests.cpp/8.1.0/?user=_&channel=_

**Comment by claremacrae** [comment]
@uilianries Thanks very much.

I don't entirely understand, as there are values present for e.g. imgui.... so please could someone do whatever is needed to copy the values in for ApprovalTests - or tell me how to do it...

**Comment by uilianries** [comment]
@claremacrae imgui has values because it was maintained by Bincrafters. As Bincrafters member, I can say, we have a script which updates it automatically. 

However, if you check the new imgui package in Bintray, https://bintray.com/conan/conan-center/imgui%3A_ , it doesn't contain any value.

I think only few people has access to change anything there in conan-center channel. But I can say the best option is integrating the hook to update it automatically, as we did for Bincrafters. The last agreement between Conan Devs was using Conan Center the truth page for package, and deprecating Bintray as package frontend. I see no problem adding information there, as it's a public page and anyone is able read.

**Comment by claremacrae** [comment]
Thanks @uilianries for this. 

That link gives a 404 for me. (https://bintray.com/conan/conan-center/imgui%3A)
Ah - I need to paste in the underscore [https://bintray.com/conan/conan-center/imgui%3A_](https://bintray.com/conan/conan-center/imgui%3A_)

I still don't really understand - To be honest, as a complete Conan novice, I'm finding the mixture of terminology and systems very confusing right now, and unfortunately I really don't have time to read through the volume of Conan docs - and I also don't want to waste your time asking you ever-more-detailed questions.

I just want to make this Conan integration available to users of ApprovalTests.cpp, and make sure I am not giving them incorrect or misleading information.

I'll try a different approach: 

> But I can say the best option is integrating the hook to update it automatically, as we did for Bincrafters.

Who would need to do that? And how?

Or should we just forget about this for now and close the ticket, and wait for it to be fixed centrally?

**Comment by uilianries** [comment]
> I still don't really understand - To be honest, as a complete Conan novice, I'm finding the mixture of terminology and systems very confusing right now

It occurs because Conan's server changed 3 times. But we keep the legacy, otherwise we could break some user. Bintray is the main server, where all official Conan packages are keeped. It's separated by remotes, the official one is [Conan Center](https://docs.conan.io/en/latest/uploading_packages/remotes.html#conan-center). In the past, the packaging process was more complicated, because you needed to write recipe, configure all CI stuff (travis, appveyor, ...), upload the packages to your Bintray account and request the inclusion to Conan Center.

Now it's [pretty easier](https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html?), you just need to open a PR with the recipe and that's it. However, Bintray still is the main server, and Conan Center still is the official Conan remote (remote is the channel where you get the packages).

> I just want to make this Conan integration available to users of ApprovalTests.cpp, and make sure I am not giving them incorrect or misleading information.

The new consensus is using the [Conan Center Index](https://conan.io/center/) front page for searching and package detail. Because it's more friendly and flexible in terms of feature to be implemented. For instance, Bintray is an universal server, so any change there will affect also Go, Java, ...


> Who would need to do that? And how?
> Or should we just forget about this for now and close the ticket, and wait for it to be fixed centrally?

I can say we can close this ticket and use https://conan.io/center instead. Bintray no longer represents the page for package details.


We have the [Bintray Updater](https://github.com/conan-io/hooks/blob/master/hooks/bintray_updater.py) hook, which can "fix" your request. Maybe @danimtb can help us with it.

**Comment by danimtb** [comment]
Here is the right link https://conan.io/center/approvaltests.cpp/8.1.0/?user=_&channel=_

All packages from this repo should be available at https://conan.io/center

**Comment by claremacrae** [comment]
Thanks @danimtb 

That link also does not work, when viewed on the GitHub site (and also in my email).

What happens is:

* any URL that ends with a trailing underscore `_` doesn't work when pasted in to a GitHub edit field
* as the GitHub markdown renderer does not treat the `_` as part of the URL - it strips it off.

For those links to work, i.e. include the underscore in the URL they represent, they would need to be pasted in as `[URL](URL)`

**Comment by danimtb** [comment]
You are totally right @claremacrae, I did not notice this was an issue in the github comments. I have updated my previous comment to the `[URL](URL)` format. I will tag this as a web issue to see if we can do something with those underscores.

**Comment by claremacrae** [comment]
Thanks @danimtb ...

Funnily enough, on closer inspection the revised comment is now odd in a different way... Whilst the hyperlink works, the two underscores get interpreted as italic in the rendered link! 

![2020-02-03 14 37 28 github com 1dfbecb61ccc](https://user-images.githubusercontent.com/4840096/73661883-c4413a00-4692-11ea-8a7e-6270e07fa364.png)

**Comment by danimtb** [comment]
Updated the comment above with escaped the underscores -- finally looks and works as expected

**Comment by Croydon** [comment]
I think that it would be nice if the website would assume for `user` and `channel` parameters `_` as the default value when omitted from the URL, so that

`https://conan.io/center/approvaltests.cpp/8.1.0/?user=_&channel=_`

gives the same result as

`https://conan.io/center/approvaltests.cpp/8.1.0/`

**Comment by danimtb** [comment]
Yes, this is something to improve in the UI

**Comment by danimtb** [comment]
this is fixed now and the new urls just look like this one https://conan.io/center/approvaltests.cpp/8.1.0/
