### ISSUE TITLE
[package] 7zip/19.00: Circular dependency when building from source

### ISSUE THREAD

**Issue by thorntonryan** [conan-io/conan-center-index#780]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **7zip/19.00**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2017 15.9.14**
  * Docker image: **N/A**
  * Conan version: **conan 1.21.2**
  * Python version: **Python 3.7.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86
arch_build=x86
build_type=RelWithDebInfo
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

1. Launch Visual Studio dev prompt (x86 Native Tools Command Prompt for VS2017)
2. `conan install 7zip/19.00 -s arch_build=x86 -s arch=x86 --build missing`
3. Receive the following error:
    `ERROR: Loop detected: 'msys2/20161025' requires '7zip/19.00' which is an ancestor too`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
C:\projects\conan-qt>conan install 7zip/19.00@ -s arch_build=x86 -s arch=x86 --build missing
Configuration:
[settings]
arch=x86
arch_build=x86
build_type=RelWithDebInfo
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ERROR: Loop detected: 'msys2/20161025' requires '7zip/19.00' which is an ancestor too

C:\projects\conan-qt>conan install msys2/20161025@ -s arch_build=x86 -s arch=x86 --build missing
Configuration:
[settings]
arch=x86
arch_build=x86
build_type=RelWithDebInfo
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ERROR: Loop detected: 'lzma_sdk/9.20' requires 'msys2/20161025' which is an ancestor too

C:\projects\conan-qt>conan install lzma_sdk/9.20@ -s arch_build=x86 -s arch=x86 --build missing
Configuration:
[settings]
arch=x86
arch_build=x86
build_type=RelWithDebInfo
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ERROR: Loop detected: '7zip/19.00' requires 'lzma_sdk/9.20' which is an ancestor too
```

</details>

**Comment by thorntonryan** [comment]
Trying to workaround cross-compiling issues with libiconv (#332) by using `-s arch_build=x86` and discovered I couldn't build 7zip from source.

**Comment by thorntonryan** [comment]
Looks like 7zip wants to have `7zr.exe` from the LZMA SDK. 
https://github.com/conan-io/conan-center-index/blob/94ded94f61a5be585b074b8a816b96217b0e5228/recipes/7zip/19.00/conanfile.py#L32-L34
If it can't find `7zr.exe` in path, it tries to build the LZMA SDK, which fails (also due to circular reference).

I can break the dependency chain by adding `7zr.exe`  manually by downloading the [LZMA SDK](https://www.7-zip.org/sdk.html) and adding it to PATH prior to running `conan install`

**Comment by Croydon** [comment]
Ironically, the main idea of using lzma_sdk within 7zip was to break circular dependencies.

Maybe we can make msys2 not relying on 7zip (are there other source downloads available?) or lzma_sdk not on msys2

**Comment by puetzk** [comment]
It's looks like msys2 is downloading .xz files, not .7z files. 

https://github.com/conan-io/conan-center-index/blob/25f0751b56e7c95bd0e8b23326c88adaf825f945/recipes/msys2/all/conanfile.py#L49-L51

Python has supported lzma and xz in the standard library since 3.3 (https://docs.python.org/3/library/lzma.html). I think conan now requires >= 3.5, so perhaps the recipe could just use that and not a build_requires tool at all?

In fact, I believe tools.untargz() (and hence tools.get() are actually implemented in terms of python's tarfile module (https://docs.python.org/3.3/library/tarfile.html), which understand .tar.bz2 and .tar.xz already (also since 3.3). So you probably don't need an outside tool and could just use tools.get(), though that already-existing support should be documented if a foundational package of conan-center-index like msys2 is going to depend on it.

**Comment by Croydon** [comment]
Conan still supports Python 2.7, so we can not rely yet on Python's lzma/xz support unfortunatly

**Comment by puetzk** [comment]
Hmm. Well, the build_requires is apparently already has behavior conditional on having 7zr in `PATH`. Would it make sense to also/instead make the msys2 build_requires conditional on python version, and use tools.untgz if python is >= 3.3 and has xz support? That would at least limit the scope of the issue to those using python 2 (who would get status quo)

**Comment by shelper** [comment]
any update on this? i am still seeing error like below on windows.
```
ERROR: Loop detected: 'lzma_sdk/9.20' requires 'msys2/20190524' which is an ancestor too
```

**Comment by Mirko-von-Leipzig** [comment]
I have run into this issue. Is there a work-around?

**Comment by SteffenL** [comment]
I am no longer able to build my own project because of this issue. It does not seem possible to break the dependency anymore since #1373 was merged.

**Comment by SteffenL** [comment]
I found the reason why overriding the recipe version didn't work in my case. It's an experimental feature that must be enabled explicitly.

https://docs.conan.io/en/latest/versioning/revisions.html#how-to-activate-the-revisions

**Comment by SteffenL** [comment]
I just found out that my build was broken because of this issue despite it working before.

#1373 removed the option to use `7zr` from the `PATH` environment variable and therefore we now always have the circular dependency.

One way to work around this issue is to override the revision of the `7zip/19.00` requirement in our conanfile to the last working revision, e.g. `7zip/19.00#dc40ec665fdf7b259bd9fa22c26368ac`.

Note that [package revisions](https://docs.conan.io/en/latest/versioning/revisions.html) is an experimental feature that must be enabled (see "[How to activate the revisions](https://docs.conan.io/en/latest/versioning/revisions.html#how-to-activate-the-revisions)").

**Comment by SteffenL** [comment]
I just found out that my build was broken because of this issue.

#1373 removed the option to find `7zr` on the system using the path environment variable and therefore we now always have the circular dependency:

    msys2/20190524 > 7zip/19.00 > lzma_sdk/9.20 > msys2/20190524

I came up with the following workarounds.

## Workaround 1

Specify the `CONAN_BASH_PATH` environment variable with the path to the Bash shell.

Git with Bash:

    set CONAN_BASH_PATH=C:\Program Files\Git\bin\bash.exe

WSL:

    set CONAN_BASH_PATH=C:\Windows\System32\bash.exe

I haven't checked whether this has to be a valid path.

## Workaround 2

Override the revision of the `7zip/19.00` requirement in your conanfile to the last working revision, e.g. `7zip/19.00#dc40ec665fdf7b259bd9fa22c26368ac`.

Note that [package revisions](https://docs.conan.io/en/latest/versioning/revisions.html) is an experimental feature that must be enabled (see "[How to activate the revisions](https://docs.conan.io/en/latest/versioning/revisions.html#how-to-activate-the-revisions)").

**Comment by VladAdGad** [comment]
Problem still exists

**Comment by LeeRuns** [comment]
Yes the problem does still exist, I was able to hack by pushing back the lzma_sdk version to 19.  That is definitely not a long term solution.
