### ISSUE TITLE
[service] remove diligentgraphics-* recipes

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#8151]
These recipes were originally added for diligentcore recipe:
 https://github.com/conan-io/conan-center-index/pull/7804#issuecomment-975161958

They should build 3rd party lib forks from Diligent as discussed here:
https://github.com/conan-io/conan-center-index/pull/7826

As I have managed to build diligent with the latest versions of the official recipes, there is no need for these diligentgraphics-* recipes recipes, please delete them

**Comment by SSE4** [comment]
sorry, but we're not removing any recipes. conan-center is immutable, as recipes will be always there.
there might be already consumers who consume that specific recipe (e.g. via lockfiles).
we can only deprecate it and discourage consumers from using it.

**Comment by AndreyMlashkin** [comment]
They were added a couple weeks ago for one specific purpose, I don't think anyone is interested in these recipes

**Comment by ericLemanissier** [comment]
You could make the recipe empty, and always raise an exception in validate, but it's a bit harsh to consumers

**Comment by SSE4** [comment]
> You could make the recipe empty, and always raise an exception in validate, but it's a bit harsh to consumers

for the record, it will be a new recipe revision. for consumers who rely on the specific (previous) revision, it won't change.

**Comment by SpaceIm** [comment]
Removing these recipes from the repo is fine I think, it doesn't mean that they are removed from conan-center.

**Comment by ericLemanissier** [comment]
I'd say it better to live a message with an exception as a first step, the remove completely (requiring admin rights, because the bot does not agree to remove folders)

**Comment by SSE4** [comment]
> I'd say it better to live a message with an exception as a first step, the remove completely (requiring admin rights, because the bot does not agree to remove folders)

yes, CI will fail for such PR. ofcourse, we can force merge it manually, but I don't want to open pandora's box right now. we already know an unfortunate `leftpad` precident, and if people will start to remove recipes they contributed in the past, it may ruin other people's workflows.

I will propose this case for the next internal discussion within our development team and let you know about our decision.
I can imagine there will be valid cases where we may want to remove some recipes (e.g. if we discover they contain some malicious code, or proprietary/leaked code). that's obviously not the case of `diligentgraphics`, but if you think it's something to remove because it's harmful, we may consider doing an exception.

**Comment by Croydon** [comment]
I would rather want to keep the recipes in git, so that names are not re-used by accident (unlikely in this case, but rules should be stringent).

**Comment by danimtb** [comment]
We discussed this topic and we agreed to handle it the same way we did with other recipes. Adding the `deprecated` attribute should be enough https://docs.conan.io/en/latest/reference/conanfile/attributes.html#deprecated. We don't have a special treatment in the CI pipeline to avoid building deprecated recipes yet, but that would be a future improvement.

**Comment by ericLemanissier** [comment]
the recipes are now mark deprecated, so this issue can probably be closed right ?
