### ISSUE TITLE
[package] libcurl/7.79.1: threaded-resolver configuration

### ISSUE THREAD

**Issue by robsussman** [conan-io/conan-center-index#8345]
This is part feature request and part bug report. The feature request is to support enabling the libcurl threaded resolver without enabling c-ares. The bug report is that enabling the c-ares option in the current conan package will also enable the threaded resolver. However, while I could not find clear documentation on this, the CMakeLists.txt looks like it disable the threaded resolver when c-ares is enabled. Details below. 

First, the conanfile.py for libcurl: 
https://github.com/conan-io/conan-center-index/blob/master/recipes/libcurl/all/conanfile.py
enables the threaded resolver when c-ares is enabled: 
`"--enable-threaded-resolver={}".format(yes_no(self.options.with_c_ares)),`

However, the CMakeLists.txt for libcurl:
https://github.com/Seagate/curl/blob/master/CMakeLists.txt
Forces the `ENABLE_THREADED_RESOLVER` option to `OFF` if c-ares is enabled:
`cmake_dependent_option(ENABLE_THREADED_RESOLVER "Set to ON to enable threaded DNS lookup"
        ON "NOT ENABLE_ARES"
        OFF)`
My read on the above is that the `cmake_dependent_option` "depends" condition of `NOT ENABLE_ARES` indicates that the threaded resolver will be forced to `OFF` when ENABLE_ARES is true. Put more simply, the `ENABLE_THREADED_RESOLVER` option depends on `NOT ENABLE_ARES` being true. 

Please take a look and let me know if something is not clear or if I'm misinterpreting. Thanks!

**Comment by ekondis** [comment]
https://github.com/conan-io/conan-center-index/pull/10357 is highly related to this issue

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.
The `libcurl/7.79.1` version is no longer supported by Conan Center Index.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported.
If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
