### ISSUE TITLE
[package] glib/2.70.0: undefined symbol: g_module_open_full

### ISSUE THREAD

**Issue by Renari** [conan-io/conan-center-index#8567]
I've currently running into issues with this in `libgio-2.0.so.0`. Checking the lib these calls are undefined. I haven't had a chance to look at the glib build yet to determine why these are undefined.
```
readelf -sW ~/.conan/data/glib/2.70.0/_/_/package/8a115f4ad0ef24579bd672a660de9899b3961a12/lib/libgio-2.0.so.0 | grep g_module_open_full
   403: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND g_module_open_full
  9412: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND g_module_open_full
```

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **glib/2.70.0**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 10**
  * Conan version: **conan 1.43.2**
  * Python version: **Python 3.8.10**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os.distro=Ubuntu20
os_build=Linux
[options]
[build_requires]
[env]
```

**Comment by Renari** [comment]
I was able to work around this issue by forcing the glib 2.6.

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.
The `glib/2.70.0` version is no longer supported by Conan Center Index.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported.
If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
