### ISSUE TITLE
[package] qt/6.2.2: Static builds are broken

### ISSUE THREAD

**Issue by cajus** [conan-io/conan-center-index#9224]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/6.2.2**
  * Operating System+version: **Linux Fedora 35**
  * Compiler+version: **GCC 11**
  * Conan version: **conan 1.44.1**
  * Python version: **Python 3.10.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Profile is attached in the sample tgz.
```

### Steps to reproduce

Unpack the attached mini project and run

```
$ mkdir build && cd build
$ conan install --build=missing --profile ../profiles/linux.gcc.11 ..
$ cmake ..
```
in the extracted dir.

The first thing that happens is that the TYPE check returns _INTERFACE_LIBRARY_ instead of _STATIC_LIBRARY_. If you comment the `if/endif` to make it assume that it's static, it tries to compile, but it doesn't find some symbols, sitting in the QtSvgPlugin.

If you add this library it links, but it will not start, because there is no single QPA linked in by default. Not only QPAs. If you dig deeper, you'll notice that it doesn't find *anything* which resides in the plugin directories. Every single plugin needs to be added via `Q_IMPORT_PLUGIN`, leading to massive `target_link_library` magic in *CMakeLists.txt*, where it's partly tricky to get the correct lib dir path.

The attached example works fine with a local lazy `./configure -static` build. It *feels* like the generated conan *FindQt6.cmake* logic is breaking stuff.

[qt-test.tar.gz](https://github.com/conan-io/conan-center-index/files/7981509/qt-test.tar.gz)

**Comment by ericLemanissier** [comment]
Thanks for the report.
about the type being INTERFACE_LIBRARY, I think this is something which would have to be fixed at the generator level (cmake_find_package, cmake_find_package_multi, CMakeDeps). Can you please report this on https://github.com/conan-io/conan ?

regarding the automatic linking of plugins, I tried something in https://github.com/conan-io/conan-center-index/pull/7378, but I failed because of the cyclic dependencies between them, which cannot be represented by conan. Maybe you want to try something ?

**Comment by cajus** [comment]
@ericLemanissier regarding #7378, I'm not sure if there's more time to look at it. I already spent a whole week in cmake debugging now, and I need a break for that. It's so frustrating. These new style conan cmake generators may work well with simple packages, but it feels like the old recipe I'm using (which keeps the original Qt cmake scripts intact) is more promising.

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.
The `qt/6.2.2` version is no longer supported by Conan Center Index.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported. 
If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
