### ISSUE TITLE
[service] source files are randomly missing in Windows builds

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#964]
sometimes there are no source files in Windows builds. each time the files are different. seems to be random, happens only on Windows so far.

e.g. https://github.com/conan-io/conan-center-index/pull/957:
```
NMAKE : fatal error U1073: don't know how to make '.\crypto\asn1\tasn_new.c'
NMAKE : fatal error U1073: don't know how to make '.\crypto\x509\x509cset.c'
NMAKE : fatal error U1073: don't know how to make '.\crypto\x509v3\v3err.c'
NMAKE : fatal error U1073: don't know how to make '.\crypto\x509v3\v3_enum.c'
```
and https://github.com/conan-io/conan-center-index/pull/906:
```
    copy /b "C:\J\c3ipr\pr_906_9_12_108\.short\3f0d6b\1\boost_1_72_0\boost\filesystem.hpp" + this-file-does-not-exist-A698EE7806899E69 "C:\J\c3ipr\pr_906_9_12_108\.short\6ff689\1\include\boost\filesystem.hpp"



The system cannot find the path specified.
```
it might be related to disk space or some disk cleanup script.

**Comment by danimtb** [comment]
I have also seen the following trace:

```
boost/1.70.0: Configuring sources in C:/J/c3ipr/custom_issue962boost_0_5/.short\e63ff7\1


JSON file created at 'C:\J\c3ipr\custom_issue962boost_0_5\_create.json'
ERROR: boost/1.70.0: Error in source() method, line 145
	tools.get(**self.conan_data["sources"][self.version])
	FileNotFoundError: [Errno 2] No such file or directory: '.\\boost_1_70_0\\libs\\geometry\\doc\\html\\geometry\\reference\\spatial_indexes\\boost__geometry__index__rtree\\rtree_parameters_type_const____indexable_getter_const____value_equal_const____allocator_type_const___.html'
```

but it only happens in Custom builds (internal Jenkins task), not in the Jobs for PRs or merge. I don't know why

**Comment by SSE4** [comment]
the one you listed might be because of too long path?

**Comment by danimtb** [comment]
yes, it could be the reason for that case. But I don't know why it only fails on the internal builds and not in the PRs' ones

**Comment by madebr** [comment]
I think I was bitten by this in #1016 
Multiple concurrent boost builds on the same machine can consume a lot of disk space.

**Comment by jmarrec** [comment]
I'm hitting the same locally when building boost/1.71.

Plenty of `this-file-does-not-exist` in the log.

------

Context:

With the latest version of `boost/1.71` following this commit https://github.com/conan-io/conan-center-index/commit/a09f5925095eaca10c162692fed8f2b001a0ef80 (we use conan_cmake_run passing `UPDATE` argument, so new versions are downloaded when they are released...), my MSVC build suddenly stopped working. I also just today updated MSVC to 16.5.1 which bumped my _MSC_VER from 1924 to 1925, so it's possible it was due to that.  Anyways, suddenly the imports are not working.

eg:

```
Error	C1083	Cannot open include file: 'boost/preprocessor/array/pop_back.hpp': No such file or directory (compiling source file C:\...\MyFile.cpp)	C:\.conan\b431f3\1\include\boost\preprocessor\array.hpp	20	
```

So I thought I'd try to build locally

**Comment by danimtb** [comment]
We have disabled the path limitation in all our windows agents and that has unblocked some pending PRs. We will keep investigating if there is any similar issue.

**Comment by danimtb** [comment]
We have done some changes around windows paths that may have improved this issue (I am not aware of any additional report). The path limitation was removed in the windows agents and the short path folder was moved to the job workspace to avoid weird locations or temp directory issues. If you have any similar case, please report it. Otherwise, we may want to close this as solved. Thank you!
