### ISSUE TITLE
[package] qt/5.13.3: with_icu option not available for Windows

### ISSUE THREAD

**Issue by sebhmg** [conan-io/conan-center-index#9910]
`qt::with_icu` option is not available for Windows, despite Qt itself supports it and ICU has a recipe for Windows.
Would it be possible to allow this option again for Windows?

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.13.3**
  * Operating System+version: **Windows 10 Pro**
  * Compiler+version: **VS 2017 tooolset v141**
  * Conan version: **conan 1.46.2**
  * Python version: **Python 3.7.8**

### Conan profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=17
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
My conanfile:
```
[requires]
boost/1.72.0
eigen/3.3.7
gdal/3.4.1
glew/2.1.0
glib/2.71.3 # also a qt dependency
glm/0.9.9.7
gtest/1.10.0
hdf5/1.12.1
icu/70.1 # is it needed if qt not configured with icu?
nanoflann/1.3.2
nlohmann_json/[>3.9.1]
openssl/1.1.1m # also a qt dependency
qt/5.15.3
zlib/1.2.11 # also a qt dependency

[options]
# Qt options
qt:qtimageformats=True
qt:qtsvg=True
qt:qttranslations=True
qt:qtwinextras=True
qt:with_glib=True
qt:with_mysql=False
qt:with_openal=False
qt:with_pq=False
qt:with_sqlite3=False
# TODO: use ICU, but Conan exposes the qt:with_icu option for Linux only

# as shared libraries
gdal:shared=True
glib:shared=True
glew:shared=True
hdf5:shared=True
icu:shared=True
openssl:shared=True
proj:shared=True
qt:shared=True
zlib:shared=True

[generators]
visual_studio
```

**Comment by sebhmg** [comment]
thanks for the clarification @ericLemanissier. I do not know if that issue is fixed, however it seemed it was for static builds only. Here, I am building Qt as a shared library.

**Comment by sebhmg** [comment]
reading the comment from @kkoehne I see it might not bring value for Windows:

> From Qt 5.0 to Qt 5.4 (I believe) we were recommending using ICU also on Windows. Anyhow, this is a very heavy dependency for people that want to deploy their  stuff, so in newer Qt versions we're using the native Windows API's for what we're using ICU for. There's some API where using ICU provides additional features (e.g. for QCollator::setNumericMode), but for most apps it's really not needed.

So I will assume we do not need it anymore, until we have a use case proving otherwise.

**Comment by sebhmg** [comment]
it turns out our application uses QCollator::setNumericMode(true), which requires ICU for natural ordering to work.

**Comment by ericLemanissier** [comment]
Feel free to make a PR changing the default value of `with_icu` to `False` and remove the line `del self.options.with_icu` (can be done both for qt5 and qt6). If you find that it works for you, I'll approve it.

**Comment by sebhmg** [comment]
pursuing our work on using Conan, and doing further testing, it appears the natural sorting works well on Windows without ICU in Qt 5.15.
The issue was only with Qt 5.12.

**Comment by benjaminc-mirageoscience** [comment]
Hi all,

After some investigations, it seems that ICU is needed if the locale ["C"](https://doc.qt.io/qt-5/qlocale.html#c) is used, as in the Qt code `QCollator::compare` (in `qcollator_win.cpp`) performs a simple string comparison if the locale "C" is used. In the equivalent function when using ICU (in `qcollator_icu.cpp`), there is no such a check of if the language is "C". After testing, natural sorting indeed does not work in Qt 5.15.8 without ICU when using the locale "C" (does work with at least some other locales, I did not try all of them). I did not test this case, but it is likely that natural sorting would work with the locale "C" if ICU is used.

In Qt 5.15.2, it works with and without ICU. After some investigations, it seems that the default constructor of `QCollator` used the system locale, instead of the locale set with `QCollator::setDefault`, as indicated in Qt documentation. In our case, we set the default locale to "C" but at the end, the natural sorting used the system locale, so natural sorting worked. In Qt 5.15.8, testing showed that the default constructor of `QCollator` did use the locale set with `QCollator::setDefault`, so Qt 5.15.2 must have a bug which was fixed in a later patch.

What do you think @ericLemanissier and @sebhmg ?

**Comment by sebhmg** [comment]
Thanks @benjaminc-mirageoscience. I suppose it is not common practice to set QLocale to "C", which means natural sorting will work on Windows without ICU in most use cases. If so, I see little need to change the recipe.
