### ISSUE TITLE
[package] sdl/2.0.16: Unable to initialize SDL with SDL_INIT_AUDIO

### ISSUE THREAD

**Issue by bolducke** [conan-io/conan-center-index#9943]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: sdl/2.0.16
  * Operating System+version: Manjaro Arch Linux 21.2.4
  * Compiler+version: gcc 11.2.0
  * Conan version: conan 1.44.1
  * Python version: Python 3.10.2

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

* Install sdl. 
* Call SDL_Init(SDL_INIT_AUDIO)

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

if no options set ->

![image](https://user-images.githubusercontent.com/26026137/160256475-4229b404-224c-4d93-9ddf-b42a2a15c212.png)

if sdl:nas=False ->

![image](https://user-images.githubusercontent.com/26026137/160256517-1c0eebf1-24f4-4d02-ad71-f16c8b75ebdb.png)

</details>

**Comment by LodrikMtl** [comment]
There is no issue when I install SDL locally

**Comment by andoalon** [comment]
The same happened to me, also in manjaro, but I didn't check if it worked if I used the system SDL and I don't remember the exact version 😅

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.
The `sdl/2.0.16` version is no longer supported by Conan Center Index.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported.
If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
